### ISSUE TITLE
New mod request: character_creator

### ISSUE THREAD

**Issue by Rui914** [minetest-mods/minetest-mods.github.io#1]
https://github.com/Rui914/character_creator

Mod name: Character Creator for Minetest
Author: Rui914
Textures license: CC BY-SA 3.0 (by Voxelands)
Source code license: WTFPL

A question: Is allowed backport to author's mod from minetest-mods?

**Comment by sofar** [comment]
I've sent you a group invitation, please accept it.

After you accept the github group invite, we can setup your git tree.

You're absolutely allowed to use the repository in anyway you see fit - backporting and merging patches are certainly perfectly ok!

**Comment by sofar** [comment]
Edit: It seems the easiest way to setup new trees is to fork your current tree, and then to grant you access. I have done this, and you should be able to push to this tree already.

If you want to grant other developers push access (apart from minetest-mods admins), then file a ticket on this ticket tracker!

Enjoy!
