### ISSUE TITLE
New mod request: lib_mount

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/minetest-mods.github.io#100]
- Name: [`lib_mount`](https://github.com/Panquesito7/lib_mount)
- Author: @blert2112, forked and improved by @Panquesito7.
- License: [GNU Lesser General Public License v2.1](https://github.com/Panquesito7/lib_mount/blob/master/LICENSE.md)

The author seems to be not maintaining the mod anymore.
I've made some improvements; and I think this will fit well in Minetest Mods. 🙂

**Comment by sofar** [comment]
same as the other mod - I'd prefer it if @blert2112 would transfer this and then you put your changes on top. If he's OK with that, let's go with that first.

**Comment by sofar** [comment]
now that this is moved, you should submit your chages as PR's to minetest-mods/lib_mount. Thanks @blert2112.

**Comment by Panquesito7** [comment]
Done for both repositories.
BTW, I'd like to also maintain both mods, as I plan to add more stuff. 🙂
