### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by Festus1965** [minetest-mods/minetest-mods.github.io#101]
Hi, 

I see your Idea, but your Mod List is quite short.
Might be to see if important or not.

I just might offer one mod, that I found an is very well to find out your personal (location ping based) server times.
I had to correct one issue, so i Cant link to original, but it is shown how did it.

http://gitea.minetest.one/Festus1965/Minetest-ping-sort

"The ping-meter in-game is from the announce server.
Doesn’t reflect your speed, unless you live nearby it.

Spend a minute to find the server nearest you, for the fastest gaming response."

Greets
Thomas / Festus / Minetest.one
collected over 1.500 mods into gitea.minetest.one last 3 days.

**Comment by sofar** [comment]
Almost 200 mods... quite short? heh.

The project linked above is not a minetest lua mod. As such it doesn't belong in this organization. It's more something for e.g. github.com/minetest-tools or similar.

**Comment by sofar** [comment]
Note: this organization isn't just to "collect" them. This organization exists to assure that these mods can be maintained by the community, with permission from the author.
