### ISSUE TITLE
Mod request: pencil

### ISSUE THREAD

**Issue by Emojigit** [minetest-mods/minetest-mods.github.io#102]
I want to add my pencil mod in minetest-mods
The code are here: [https://github.com/Emojigit/minetest-pencil](https://github.com/Emojigit/minetest-pencil)
author: Me (Emojigit)
license: 
- For The Code: MIT
- For Media: LGPL, CC BY-SA, Unknown

**Comment by SmallJoker** [comment]
Invitation sent, @Emojigit.
If this works for you, go to your repository's settings and transfer it to minetest-mods.

**Comment by Emojigit** [comment]
I joined the modding team, but i still can't transfer the repo.

**Comment by Emojigit** [comment]
![螢幕截圖 2020-08-02 下午1 36 36](https://user-images.githubusercontent.com/55009343/89116317-433df080-d4c5-11ea-85b7-cbea2ac248da.png)
This is the error message

**Comment by Emojigit** [comment]
@SmallJoker

**Comment by sofar** [comment]
It doesn't work like that. Once the mod is approved, the transfer needs to be made to `sofar`. Then we transfer it through to `minetest-mods`. This is needed because a non-owner person may not transfer or create new repos in an org.

**Comment by sofar** [comment]
This is a one-mod modpack. Please change this to be a single mod instead. Modpacks should always be avoided. Please remove the toplevel folder and place the mod files (`init.lua`) directly in the toplevel folder instead.

**Comment by sofar** [comment]
The license should be with the `init.lua` files as well. Make sure not to lose that.

**Comment by sofar** [comment]
general concept is OK. I would make a formspec so that the text can dynamically be changed. That way you just need a single pencil and it can assign arbitrary values.

**Comment by Emojigit** [comment]
@sofar new reop url: https://github.com/Emojigit/pencil

**Comment by sofar** [comment]
Yeah, that's better. However, try to use `git` and not blow away changes like that - incremental changes are always safer.

Ideally you make a `mod.conf` with the proper attributes as well.

**Comment by Emojigit** [comment]
> Yeah, that's better. However, try to use `git` and not blow away changes like that - incremental changes are always safer.
> 
> Ideally you make a `mod.conf` with the proper attributes as well.

@sofar Added mod.conf!

**Comment by sofar** [comment]
I would still suggest adding a formspec method instead of the chatcommand. Being able to to "program" a pen on first use, and then re-use it over and over with a simple formspec is probably easier than a command. Especially if you make e.g. right-click show the formspec, and left-click apply the text to the node.

However, this is in the current for OK with me. @SmallJoker comments?

**Comment by SmallJoker** [comment]
No objections. I totally missed that it was a modpack - glad to see that it's fixed now.

The README could be improved further by including:
 * License (because not visible directly on the front page)
 * Minetest version requirements
 * Mod dependencies
However, this is left to each mod developer and is not a requirement for minetest-mods according to the manifest.

**Comment by Emojigit** [comment]
> No objections. I totally missed that it was a modpack - glad to see that it's fixed now.
> 
> The README could be improved further by including:
> 
> * License (because not visible directly on the front page)
> * Minetest version requirements
> * Mod dependencies
> 
> However, this (^) is left to each mod developer and is not a requirement for minetest-mods according to the manifest.

I will make the readme later.
First, this mod can run on most all version (this can run on the oldest windows pre build version)
Second, This mod have no depends
Third, This mod 's license is MIT.

**Comment by SmallJoker** [comment]
> the transfer needs to be made to sofar. Then we transfer it through to minetest-mods

@sofar - action required.

**Comment by sofar** [comment]
@Emojigit needs to initiate the transfer to me, I will get an email as soon as he does

**Comment by sofar** [comment]
If no action in the next few weeks, I will close due to inaction.

**Comment by Emojigit** [comment]
Mod outdated, close.
