### ISSUE TITLE
New mod request: cloud_items

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/minetest-mods.github.io#103]
- Name: [`cloud_items`](https://github.com/Panquesito7/cloud_items)
- Author: @Panquesito7
- License: LGPLv2.1+ for code, [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) for textures ([CC0](https://creativecommons.org/publicdomain/zero/1.0/) for [`cloud_items_multitool_cloud.png`](https://github.com/Panquesito7/cloud_items/blob/master/textures/cloud_items_multitool_cloud.png)).

**Comment by Panquesito7** [comment]
@sofar ping?

**Comment by sofar** [comment]
Oh, sorry, completely missed it. Send it in a transfer to `sofar` - it all looks OK.

**Comment by Panquesito7** [comment]
Transfer sent, thank you. 🙂
