### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mods/minetest-mods.github.io#105]
Forum post from @katp32 (https://forum.minetest.net/viewtopic.php?p=381044#p381044)
```
I understand that this isn't exactly the most convenient way of doing things (I'm trying to cut down on server-side bloat).
If someone would rather take over maintaining it themselves,
I'll happily step aside and let them move it to GitHub or wherever else they want it.
```

https://leagueh.xyz/git/katp32/playerfactions/.git

I'd like to adopt that repo into the `minetest-mods` repo after the owner gives the ok to do so

**Comment by katp32** [comment]
If that's what the community wants, it seems fair.

I will mention that I didn't abandon the mod, and never had any intention of doing so; I simply moved from one hosting solution to another. I'm still in contact with people reporting bugs via email.

I would prefer if it was hosted on an open source platform like GitLab or Gitea (such as notabug.org), but if I'm not the maintainer I guess I'm not really in a position to argue.

**Comment by SmallJoker** [comment]
@katp32 The benefit of transferring it to minetest-mods on Github is solely the large member count which is capable of reviewing PRs and fixing high priority issues. You would still have full control over the repo (unless you'd like to opt-out) to continue developing.

It is important to me that the mod author is keen moving the development to a minetest-mods repository. Otherwise it is pointless to synchronize two versions of the mod.

**Comment by katp32** [comment]
I have no interest in using GitHub to maintain the project, and I suspect that if a developer isn't capable of using software other than GitHub, they do not have any meaningful contributions to make regardless.

If it's moved to GitHub, I'm ok with that, but I will no longer have any involvement in the project. Whoever migrates it will be wholly responsible for maintaining it.

**Comment by BuckarooBanzay** [comment]
> I have no interest in using GitHub to maintain the project, and I suspect that if a developer isn't capable of using software other than GitHub, they do not have any meaningful contributions to make regardless.

Uhm, sure... a fork it is then :shrug:
