### ISSUE TITLE
New mod request: teleport request (tpr)

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/minetest-mods.github.io#107]
- Name: [Teleport request](https://github.com/Panquesito7/teleport-request).
- Author: [ChaosWormz](https://github.com/ChaosWormz).
- License: [LGPLv2.1+](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) for code, [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) for sounds.

**Comment by sofar** [comment]
Ok with me. Is there a reason @chaoswormz isn't the owner of the repo? Not that that really matters much.

**Comment by Panquesito7** [comment]
> Is there a reason @ChaosWormz isn't the owner of the repo? Not that that really matters much.

They transferred the repository to me so I can put it in Minetest Mods easily. 🙂

**Comment by Panquesito7** [comment]
The transfer has been sent. Thank you.
