### ISSUE TITLE
List of my mods

### ISSUE THREAD

**Issue by rubenwardy** [minetest-mods/minetest-mods.github.io#11]
Here is a list of my mods that I consider ready:

- [ ]  https://github.com/rubenwardy/forceload
- [x]  https://github.com/rubenwardy/jump
- [x]  https://github.com/rubenwardy/diet
- [x]  https://github.com/rubenwardy/aliases
- [x]  https://github.com/rubenwardy/vote
- [x]  https://github.com/rubenwardy/awards
- [x]  https://github.com/rubenwardy/smartfs (a library, probably doesn't count)
- [x]  https://github.com/rubenwardy/privilegeareas (not tested recently)

For reference, excluded mods:

* https://github.com/rubenwardy/email (needs research, possibly made obsolete by other mods
* https://github.com/rubenwardy/chatplus (see above)
* https://github.com/rubenwardy/report (see above)
* https://github.com/rubenwardy/coffee (experimental prototype)
* https://github.com/rubenwardy/traps (old mod)
* https://github.com/rubenwardy/food (Currently uses a modpack)
* https://github.com/rubenwardy/food_sweet (depends on food)
* https://github.com/rubenwardy/food_english (depends on food)
* https://github.com/rubenwardy/food_modern (depends on food)
* https://github.com/rubenwardy/waterplus (old mod)
* https://github.com/rubenwardy/alien (experimental prototype)
* https://github.com/rubenwardy/ctf_pvp_engine (I want to keep for now, is unstable)

I'd like feedback on which of these you'd like, then I can start transfering them across and updating forum topics.

**Comment by sofar** [comment]
Code wise they look fine. I did miss a license statement on diet and privilegeareas. Of course mod.conf and description.txt's are missing almost everywhere, which I'd like to see fixed. Perhaps assure screenshots are added where relevant (email, chatplus, others?)

**Comment by rubenwardy** [comment]
Ok, I will do this soon.

**Comment by sofar** [comment]
Maybe do one or two already so you get slowly through this one by one?

**Comment by sofar** [comment]
@rubenwardy ready to close this for now?
