### ISSUE TITLE
Please give the Minetest Game mods a new home

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#112]
Minetest Game contain a lot of useful mods, but the game is in [Mainanance only mode](https://github.com/minetest/minetest_game/issues/2710). That means no further development is possible for included mods. :-(

Therefore I ask to give the MTG-Mods a new home in minetest-mods, each mod separately. 

I am specifically concerned with player_api mod because of https://github.com/minetest/minetest_game/pull/2122 and 
sfinv because of features in https://github.com/minetest-mods/smart_sfinv

**Comment by AntumDeluge** [comment]
Agreed.

**Comment by AntumDeluge** [comment]
I found out from wsor that @BuckarooBanzay keeps the individual mods updated [here](https://github.com/minetest-game). But still would be nice to get them added to ContentDB so individual mods don't have to depend so heavily on MTG.

**Comment by sofar** [comment]
Not immediately opposed, but they have their place where they are right now, and not in this organization. If the existing github org is going to be abandoned, then we can revisit.

**Comment by AntumDeluge** [comment]
[sfinv](https://content.minetest.net/packages/rubenwardy/sfinv/) is actually already independent from MTG.

**player_api** is definitely an important one as there are so many mods available on ContentDB that depend on it.

**default** is one that too many mods depend on. Rather than that getting a new home, it should probably be replaced with multiple mods of different functionality. But I think there is a whole discussion on that subject somewhere.

**Comment by AntumDeluge** [comment]
Note that MTG game mods have been forked & hosted at [minetest-game-mod](https://github.com/minetest-game-mod). But the repos are marked read-only. So I don't think they are updated. They have just been separated to make it easier for others to fork & use.

**Comment by BuckarooBanzay** [comment]
> Not sure if this is an official organization unlike [minetest-game](https://github.com/minetest-game), but it has commits from core & MTG developers.

The `minetest-game` org isn't official, just fyi :wink: just something i started out of a need

The repos _should_ be updated daily through the `repo_slicer` actions but those get stopped after some inactivity on the repo, not sure if it was one or two months. If someone has improvements there or wants to join in on the org be my guest...

**Comment by sfan5** [comment]
I agree this isn't the place.
