### ISSUE TITLE
add `technic_armor`

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mods/minetest-mods.github.io#113]
Original repo is abandoned, same as with `3d_armor`

Repo: https://github.com/stujones11/technic_armor
Improved and forked repo: https://github.com/mt-mods/technic_armor (linting and translations)

Relevant discussion: https://github.com/minetest-mods/3d_armor/pull/47

Suggested maintainers:
* @BuckarooBanzay (bugfixes, testing)
* @Panquesito7 (bugfixes, translations)
* @AntumMT (contributes to the base-mod and has good ideas)

**Comment by sofar** [comment]
Is this for the improved/forked version? or for the original - just asking for clarity sake.

**Comment by BuckarooBanzay** [comment]
> Is this for the improved/forked version? or for the original - just asking for clarity sake.

Yeah, sorry, lost track of this :/
Meanwhile we adopted that mod fully now under the `mt-mods` umbrella, no need to import it here, sorry for the trouble
