### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by tagacraft** [minetest-mods/minetest-mods.github.io#115]
Hello,
Hope i have done this request fine;
I wrote a mod (tested) to easily add some usefull settings on a game, like :
- add missing recipes;
- link some nodes to some foreign mods that shape them (circular saw, pkarcs, technic_cnc, ...)
some features :
- log file separated from minetest/debug.txt, with few levels of verbose; log file rewritten each start to limit it 's size;
- server's local settings kept safe while updating the mod
- while a node is registered to a shaping mod, all characteristics from ancestor are transmitted to the shaped nodes (like light source) e.g. you can make lighting meselamp arcs;
- As i meet that issue on a server, the limit of 32767 minetest_registered_nodes[] is tested to avoid server crash at loadtime;
- a free left place amount can be set for other mods to register their nodes after mycustom;
- when an upgrade provide new settings available, the server's admin is notified ingame when he log on
- the log file specify the time spent by mycustom (usually less than 0.25 seconds (250 miliseconds) )
- easy way to add a foreign mod as a shaper mod that have a function to create new shaped nodes (e.g. moreblocks:circular_saw is a shaping mod that receive a node and create shaped nodes from it)

Mod name :  mycustom
license : no licence. Do what you want.
repository : https://github.com/tagacraft/minetest/tree/mycustom
my name : tagacraft
contact : tagacraft@free.fr

Have fun :)

**Comment by sofar** [comment]
Mods must have a valid license. "no license" is not OK. We try to explain this in our charter. Until this is changed, it cannot be considered.

**Comment by Panquesito7** [comment]
If you don't really wanna add a license, just use MIT or WTFPL (which I'm not sure if it's OK to use anymore). As sofar said, not having a license is not good. People won't know what they can and can't do with the code. 🙂

**Comment by tagacraft** [comment]
Hello, thanks for your interest;
I uploaded a modified version under MIT license as you wish, at :
https://github.com/tagacraft/minetest/tree/mycustom

Hope that is satisfying for you.
Best regards.


Le 2021-11-29 23:58, David Leal a écrit :

**Comment by sfan5** [comment]
Request rejected due to project inactivity. Sorry for the wait.
