### ISSUE TITLE
Request to transfer control of all of my Minetest-related repositories

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/minetest-mods.github.io#116]
I have decided to basically retire from most Minetest-related activities, which includes modding.

Since a lot of people rely on them, I'd like to hand-over ownership and maintenance of any or all of my Minetest-related projects hosted on my Gitlab account to someone else.  Obviously that'll require cloning them all from there to here.

This issue has been crossposted to minetest-mods and mt-mods -- the idea here is that I'm perfectly happy for either of these organizations to get my mods, just whoever wants to take on which ones.  In fact, if others outside these groups wish to take over some projects, I'm okay with that, too.

All of my projects are located at https://gitlab.com/users/VanessaE/projects

Although it's conceivable that I'll randomly find a reason to add/change something in one of my projects, I do not require commit access or anything of the kind.  That stuff can be done with ordinary pull requests.

All of the following projects need to be transferred somewhere:

**Mods**
- [X] https://gitlab.com/VanessaE/pipeworks
- [x] https://gitlab.com/VanessaE/signs_lib
- [x] https://gitlab.com/VanessaE/basic_signs
- [x] https://gitlab.com/VanessaE/street_signs
- [x] https://gitlab.com/VanessaE/homedecor_modpack
- [x] https://gitlab.com/VanessaE/home_workshop_modpack
- [x] https://gitlab.com/VanessaE/biome_lib
- [x] https://gitlab.com/VanessaE/plantlife_modpack
- [x] https://gitlab.com/VanessaE/moretrees
- [x] https://gitlab.com/VanessaE/minislots
- [x] https://gitlab.com/VanessaE/basic_materials
- [x] https://gitlab.com/VanessaE/unifieddyes
- [x] https://gitlab.com/VanessaE/autoclose_doors
- [x] https://gitlab.com/VanessaE/reboot_warner
- [x] https://gitlab.com/VanessaE/coloredwood
- [x] https://gitlab.com/VanessaE/led_marquee
- [x] https://gitlab.com/VanessaE/nixie_tubes
- [x] https://gitlab.com/VanessaE/simple_streetlights
- [x] https://gitlab.com/VanessaE/round_trunks

**Texture packs**
- [ ] https://gitlab.com/VanessaE/hdx-64
- [ ] https://gitlab.com/VanessaE/hdx-128
- [ ] https://gitlab.com/VanessaE/hdx-256
- [ ] https://gitlab.com/VanessaE/hdx-512
- [ ] https://gitlab.com/VanessaE/c64-16px
- [ ] https://gitlab.com/VanessaE/c64-64px

**Mod forks where I eventually became the maintainer**
- [x] https://gitlab.com/VanessaE/currency
- [x] https://gitlab.com/VanessaE/ilights
- [x] https://gitlab.com/VanessaE/gloopblocks
- [x] https://gitlab.com/VanessaE/steel

**RBA's old shader projects**
These shaders are unmodified from RBA's last changes, as far as I know, and probably don't work anymore, but they should still be copied over, for posterity:

- [ ] https://gitlab.com/VanessaE/water_surface_shader
- [ ] https://gitlab.com/VanessaE/shaded_lava
- [ ] https://gitlab.com/VanessaE/lava_surface_shader
- [ ] https://gitlab.com/VanessaE/water_shaders

Any open issues on the above repositories should be copied-over as well, though I don't know if there's any automated way to do that.

Any other projects found on my Gitlab profile are either outdated, or are just forks of other peoples' projects where I probably contributed something, or are unrelated to Minetest, and may be ignored.

All projects transferred to someone else will be deleted from my Gitlab account.

- [x]  ~~Once everything above has been transferred, I'll make one final release of Dreambuilder, and then it~~ Dreambuilder and its two side projects should also be transferred (https://gitlab.com/VanessaE/dreambuilder_game ~ https://gitlab.com/VanessaE/dreambuilder_themes ~ https://gitlab.com/VanessaE/dreambuilder_hotbar).

**Comment by bell07** [comment]
Your retirement is a huge loss to the Minetest community. Thank you for all the great mods you wrote and maintained last years! I hope we can find worthy successors so that your achievement will continue.

**Comment by wsor4035** [comment]
in addition to moving the mods here, the source url for the repo on contentdb will need to be changed so they keep getting updates and isnt a 404

**Comment by BuckarooBanzay** [comment]
@VanessaE fyi: i forked the `pipeworks` mod into our org: https://github.com/mt-mods/pipeworks and intend to maintain that there

**Comment by VanessaE** [comment]
Noted.  Pipeworks is scratched from the list and deleted from gitlab.

**Comment by VanessaE** [comment]
With that done, I'll reiterate here what I said in my chat yesterday:  I'm not too concerned with who gets which project, between mt-mods and minetest-mods or really anyone else, just as long as everything gets forked/transferred to good homes.

**Comment by OgelGames** [comment]
It might have been good to copy over the open issues before deleting it... Something to think about for the other repos.

**Comment by VanessaE** [comment]
Ooops, sorry about that. :disappointed: 

Oh well, they were probably all outdated anyway, and if something's important enough, someone can just open a new issue over there.

**Comment by VanessaE** [comment]
https://github.com/mt-mods/mt-mods/issues/1

**Comment by VanessaE** [comment]
Everything of importance has either been moved or appropriate parties have been pinged.
