### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by appgurueu** [minetest-mods/minetest-mods.github.io#118]
I'd like to become a member of the Minetest mods organization (ideally as a project author) to help maintain mods (approving PRs for instance) such that hacks like [this](https://gitlab.com/threehymns1/unified_inventory_themes/-/blob/main/init.lua#L3-13) can be replaced by proper APIs (for styling in this case). I'm currently on the MTG and Minetest Docs teams and have a couple own mods (which aren't part of this org though).

**Comment by sofar** [comment]
In general we look a merit to promote contributors to more privs. I definitely would like to see more active maintainers. I haven't followed with recent changes in this project but it would help if there's a list of PRs you've thoroughly reviewed that need approval so we can judge how you're doing. If you're making a solid effort to help clear out many of these then maintainership is the next logical step.

**Comment by appgurueu** [comment]
Realistically I'm not sure I would have time for this. I'll put it on hold for now.

**Comment by SmallJoker** [comment]
Sorry, I'm a bit late. I have no objections in case you'd like to reapply.
