### ISSUE TITLE
droplift

### ISSUE THREAD

**Issue by lightonflux** [minetest-mods/minetest-mods.github.io#12]
It is a mod for devs that places drops correctly on walkable nodes. 

At the moment it is only available via dropbox. It is a simple mod that would fit in this repo i think.

https://forum.minetest.net/viewtopic.php?f=9&t=14381

**Comment by sofar** [comment]
Yeah, I checked out the code and license is OK, and this sounds like an entirely reasonable and useful mod (I'd use it myself).

Is this your mod?

**Comment by lightonflux** [comment]
No it is made by aftermoth [forum](https://forum.minetest.net/viewtopic.php?f=9&t=14381) who is pretty new to MT modding.

**Comment by sofar** [comment]
If aftermoth is interested in putting it in minetest-mods, then he's more than welcome to do so. But he should be the one that initiates the request.

**Comment by sofar** [comment]
I've left a post on the forum - let's see if he responds.

**Comment by sofar** [comment]
moved to minetest-mods!
