### ISSUE TITLE
New mod request: creative

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/minetest-mods.github.io#121]
The `creative` mod is useful outside of Minetest Game. And since Minetest Game is now frozen, I think it would be good for it to be standalone. It has been [forked here](https://github.com/minetest-game-mod/creative) but repo is read-only & not accepting updates (as far as I know). I would also like to see it added to ContentDB. I am not the creator of the mod but I think this is a special case.

**Note:** The mod configuration claims that it is dependent on `default`, but from my experience that is not the case. Grepping the code I didn't find any references to `default` & I was able to run it fine under a game without `default` installed.

Related: #112

**Comment by sfan5** [comment]
Closed for same reason as #112
