### ISSUE TITLE
New mod request: player_api

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/minetest-mods.github.io#122]
For [player_api](https://github.com/minetest-game-mod/player_api), same as I said for [creative](https://github.com/minetest-mods/minetest-mods.github.io/issues/121).

There are [a lot of mods that depend on it available from ContentDB](https://content.minetest.net/modnames/player_api/).

Related: #112

**Comment by sfan5** [comment]
Closed for same reason as #112
