### ISSUE TITLE
New Mod Request: minetest-bows

### ISSUE THREAD

**Issue by IFRFSX** [minetest-mods/minetest-mods.github.io#124]
I found a very useful mod, but that has stopped maintenance.

This is a bow and arrow mod that can determine the shooting distance according to the time the player presses the button, similar to the bow and arrow in minecraft.

```https://github.com/Arcelmi/minetest-bows```
+ name: minetest-bows
+ author: Arcelmi
+ license: LGPL-3.0

This project depends on the same author's Control mod, which is currently fork and maintained by the "mt-mods" team, but in order to ensure development compatibility(minetest-bows and this mod), it is recommended to add it to minetest-mods to develop together：
```https://github.com/mt-mods/control```

+ name:control
+ author: Arcelmi & mt-mods team
+ license: LGPL-2.1

**Comment by sfan5** [comment]
Request rejected due to project inactivity. Sorry for the wait.
