### ISSUE TITLE
`mywalls` mod maintenance request

### ISSUE THREAD

**Issue by alek13** [minetest-mods/minetest-mods.github.io#125]
It seems like mod [`minetest-mods/mywalls`](https://github.com/minetest-mods/mywalls) not supported and abandoned by author [about 6 years](https://github.com/minetest-mods/mywalls/commits/master). Or maybe it was just copied to org and no more.

This mod is still actual and I can [help](https://github.com/minetest-mods/mywalls/pull/2) to [maintain](https://github.com/minetest-mods/mywalls/issues/3) it.

Can you grant me maintainer for this repo ?

**Comment by alek13** [comment]
Not sure who to mention. @sofar ? @rubenwardy ?

**Comment by sfan5** [comment]
Push access granted.
