### ISSUE TITLE
Mod request: My mod ExchangeClone

### ISSUE THREAD

**Issue by ThePython10110** [minetest-mods/minetest-mods.github.io#126]
Mod name: [ExchangeClone](https://github.com/thepython10110/exchangeclone) (originally forked from [Element Exchange](https://github.com/enchant97/minetest_element_exchange), inspired by Equivalent Exchange/ProjectE in MineCraft)
Author: Me (ThePython/ThePython10110)
Licenses:
* Code: GPLv3+
* Sounds: CC-BY-SA-3.0
* Textures:
    * Constructor, Deconstructor, and Exchange Orb (from Element Exchange): GPLv3+
    * All other textures: CC-BY-SA-3.0

Also... is this project still alive now that ContentDB exists?

**Comment by sfan5** [comment]
Request rejected due to project inactivity. Sorry for the wait.
