### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by Niklp09** [minetest-mods/minetest-mods.github.io#127]
Many minetest-mods projects are more or less dead. The main issue is IMO that no one (except Krock) merges actively PR's. Therefore, I apply to take over tasks here. I'm [contributing](https://github.com/Niklp09?org=minetest-mods&year_list=1) to some mods here, mainly maintenance and bugfixes. I'm a staff member of [mt-mods](https://github.com/Niklp09?from=2023-10-01&to=2023-10-15&org=mt-mods&year_list=1) too. If you don't want to grant me access, please consider to grant other active people like @BuckarooBanzay (if he wants) more access.

**Comment by BuckarooBanzay** [comment]
> (if he wants) more access.

i'm good and have enough projects to maintain :laughing: 

but +1 for Niklp as maintainer :+1:

**Comment by sfan5** [comment]
I've sent an invitations, please ping me again once you have accepted it.

**Comment by Panquesito7** [comment]
Great to see more active maintainers! I'm all for this. 👍

**Comment by Niklp09** [comment]
@sfan5 accepted. tyvm.

**Comment by sfan5** [comment]
Wait, do you have write access to repos already? I thought I had to grant that separately.

**Comment by Niklp09** [comment]
> Wait, do you have write access to repos already? I thought I had to grant that separately.
No, I have no write or edit access yet.

**Comment by sfan5** [comment]
Apparently github only allows me to manage role access one-by-one. I don't have time to sit here for an hour doing this for 200 repos, so I'll have to script.
Might be some days until I get to it.

**Comment by Panquesito7** [comment]
> Apparently github only allows me to manage role access one-by-one. I don't have time to sit here for an hour doing this for 200 repos, so I'll have to script. Might be some days until I get to it.

You can create a team that has access to all repositories with write access and add the members (in this case, @Niklp09). This is very easy to perform and shouldn't take long.

**Comment by sfan5** [comment]
How?
Note that I don't want to grant the "Owner" role.

**Comment by sfan5** [comment]
Okay nevermind. Scripting it in-browser was easier than expected:
```js
// add every repo to the team
await (async function() {
const src = 'https://api.github.com/orgs/minetest-mods/repos?per_page=999'; // edit to add page=2 etc.
const data = await (await fetch(src)).json();
const form = document.querySelector('details-dialog form[action$=repositories]');
const fd = new URLSearchParams(new FormData(form));
for (const x of data) {
	fd.set("member", x.full_name);
	await fetch(form.action, {
		method: form.method,
		body: fd
	});
	await new Promise(r => setTimeout(r, 200));
}
})();

// change all permissions to 'Write'
for (const e of document.querySelectorAll('.js-permission-menu-form')) {
	e.querySelector('summary').innerText !== "Write" && e.querySelector('button[value=push]').click()

```
