### ISSUE TITLE
New mod request: Diglines

### ISSUE THREAD

**Issue by Jeija** [minetest-mods/minetest-mods.github.io#13]
https://github.com/Jeija/minetest-mod-digilines

Name: Diglines
Author: Jeija
Licenses: LGPLv3 for code, WTFPL for textures etc.

I was originally intending digilines to become more than just the minimal base of items that it is now, so I'd really like to see integration of other digiline-related items (basically what digiline_stuff did, or things like VanessaE's nixie tubes). Also, the internals of digilines should propably be ported to the `vector` helper functions and craft recipes and other things should be documented. Since I don't have time to do these things, I'd say it is beneficial to all digiline users if you take over this project and extend it to what you would like it to be. Just one small request from my side: Please don't add hard dependencies on anything other than mesecons.
Thanks for the minetest-mods project!

**Comment by sofar** [comment]
Cool, this is a mod with potential.

Can you initiate a github project transfer to user "sofar". Then I move it through to Minetest-mods. You retain permissions throughout the process, of course.

**Comment by sofar** [comment]
All moved. Note that I renamed the repo to be "digilines"!
