### ISSUE TITLE
New mod request : MoreMesecons

### ISSUE THREAD

**Issue by paly2** [minetest-mods/minetest-mods.github.io#15]
Hello.

First, sorry for my bad english (there must be errors in this issue, and in the mod itself).  
I created a mod named [MoreMesecons](https://github.com/paly2/MoreMesecons), distributed under GNU General Public License version 3. @HybridDog contributed a lot - more than me.

I would like to transfer this mod to this organization. Note that it is not much developped since a few month (as you can see in [commits](https://github.com/paly2/MoreMesecons/commits/master)).

Thank you,
paly2

**Comment by sofar** [comment]
alright!

The best way to do this is to do a github transfer to user "sofar". Please initiate the transfer and I will move it through to minetest-mods. You keep access, and it retains issues, etc. during the move this way.

**Comment by paly2** [comment]
Ok, I do this immediatly
