### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by bas080** [minetest-mods/minetest-mods.github.io#17]
I would like to contribute my mods to the minetest-mods project. I would however prefer keeping my repositories and have the minetest-mods fork them instead. Saves me time when it comes to updating forum posts.

**Comment by sofar** [comment]
I'm not allowing people to do this. If you want to keep the links intact, you should move your mods to minetest-mods and then fork it back.

**Comment by red-001** [comment]
Github will setup an automatic redirect to the new location when a repository is moved.

**Comment by sofar** [comment]
That one is only temporary. Adjusting forum links and forking back are reasonable ways to deal with it.

**Comment by sofar** [comment]
@bas080 if you're OK with moving, please transfer the repo to `sofar` (and then I move it through to minetest-mods). If you're not OK, please close this issue.

**Comment by sofar** [comment]
No response, I assume it's because you don't want to move your project.
