### ISSUE TITLE
Computer

### ISSUE THREAD

**Issue by lightonflux** [minetest-mods/minetest-mods.github.io#18]
Hi there,

what about the computer mod by kaeza? Did a quick repo search on github and it looks like mt-mods does not include a computer mod.

https://github.com/kaeza/minetest-computer

It is high grade, simple and i only fear that at some point the repo might get inaccessible.

**Comment by sofar** [comment]
You should ask the maintainer to move it. I can assist, but it's up to @kaeza to make up his mind. You can ask him directly, of course.

We don't "take over" projects. We ask them to "join" instead.

**Comment by kaeza** [comment]
For the record, computer mod is part of homedecor since a long time ago.
