### ISSUE TITLE
New mod request: carpets

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest-mods/minetest-mods.github.io#19]
https://github.com/Rui914/carpets

Mod name: Carpets
Author: Rui914
License: WTFPL

**Comment by sofar** [comment]
Can you initiate a repo transfer to user `sofar`? then I'll move it through to minetest-mods.

**Comment by Rui914** [comment]
It has been transfered.

**Comment by sofar** [comment]
Thanks, but I didn't accept it - While we've added a few modpacks (sigh) in the past, I've attempted to stop proliferation of them by not accepting more.

I don't see a reason to keep a single-purpose type mod like this a modpack, so I'd like to see it converted to a normal mod first before transferring it.
