### ISSUE TITLE
Add my lapis mod

### ISSUE THREAD

**Issue by LNJ2** [minetest-mods/minetest-mods.github.io#20]
https://github.com/LNJ2/lapis

**Comment by sofar** [comment]
Go do a 'transfer' to user 'sofar' - I will then transfer it through to minetest-mods (it can't go directly that way). You retain all permissions on the tree and the history is preserved, as well as a backlink.

**Comment by LNJ2** [comment]
done

**Comment by sofar** [comment]
I'll transfer this in an hour or two.., thanks!

**Comment by LNJ2** [comment]
Still not moved?

**Comment by sofar** [comment]
I didn't get any notifications. Please cancel any existing transfers and try again.

**Comment by LNJ2** [comment]
Repository transfer to sofar requested

**Comment by sofar** [comment]
Moved!
