### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by Amaz1** [minetest-mods/minetest-mods.github.io#23]
Mod name: letters (https://github.com/Amaz1/letters)
Author: Me (@Amaz1)
License: Code: zlib (As this is what moreblocks uses, and a lot of the code comes from there) Textures: CC BY-SA 3.0

I coded this a couple of years ago, and it's pretty ugly code... I could probably do a better job now, but I don't have the time/motivation to maintain it, let alone rewrite it. Hopefully it will have someone to look after it in minetest-mods!

------------------------
Mod name: interact (https://github.com/Amaz1/interact)
Author: Me (@Amaz1)
License: MIT

A mod I wrote as a(nother) solution for new players joining a server and needing interact. While it won't prevent griefers, it will at least check that players have read the rules...!

------------------
Mod name: coloured_nametag (https://github.com/Amaz1/coloured_nametag)
Author: Me (@Amaz1)
License: MIT

A mod that allows players to change their nametag colour.

-------------------
Mod name hide_minimap (https://github.com/Amaz1/hide_minimap)
Author: Me (@Amaz1)
License: MIT

A very simple mod that only allows players with a certain priv (minimap) to view the minimap. There's also a setting to disable the minimap totally.

**Comment by sofar** [comment]
- letters == OK
- coloured_nametag == OK
- hide_minimap == OK
- interact : isn't @kaeza maintaining that mod still? I'd prefer a cooperation where he merges the improvements and we merge that into minetest mods (the "no fork rule")

For the mods that I've OK'd, please use the github webpage to initiate a 'repo transfer' to "sofar". I then transfer it through to minetest-mods. You keep all access to the repos while the transfer happens and afterwards.

**Comment by kaeza** [comment]
@sofar The [original code](http://pastebin.com/QVJw577B) (if I understand correctly what you're referring to) was released as a sort of experiment, and I never intended to develop it further.

**Comment by Amaz1** [comment]
Okay, initiated transfers for the three OKed mods!
(I've also added mod.confs and description.txts to all of them)

**Comment by sofar** [comment]
You can submit the `interact` mod as well.

**Comment by Amaz1** [comment]
Okay, done! Thank you very much!

**Comment by sofar** [comment]
All moved! Nice!
