### ISSUE TITLE
New mod request: commander

### ISSUE THREAD

**Issue by mahmutelmas06** [minetest-mods/minetest-mods.github.io#24]
Commander
mahmutelmas06
MIT

https://github.com/mahmutelmas06/commander.git

**Comment by mahmutelmas06** [comment]
Its doesnt have proper license.
Free to use and publish for personel and commercial use without linkback to author. So i would say same as code(Mit).

21 Kas 2016 20:11 tarihinde Auke Kok <notifications@github.com> yazdı:

Mostly looks OK, but I can't find any license statement for the icon - is this icon copied from somewhere?

**Comment by sofar** [comment]
It looks exactly like one of the stock kde or gnome icons, and those potentially have licenses. If you drew this yourself originally, then that's fine, but I would like to confirm that and make sure you didn't accidentally screenshot it from somewhere without checking the license.

**Comment by mahmutelmas06** [comment]
i found it.
free for commercial use

https://www.iconfinder.com/icons/103861/command_line_prompt_shell_icon#size=32

21 Kas 2016 20:47 tarihinde Auke Kok <notifications@github.com> yazdı:

It looks exactly like one of the stock kde or gnome icons, and those potentially have licenses. If you drew this yourself originally, then that's fine, but I would like to confirm that and make sure you didn't accidentally screenshot it from somewhere without checking the license.

**Comment by sofar** [comment]
Our guidelines for accepting modules talk about cases like this explicitly, to protect both you and users of your mods.

The problem with "Free for commercial use" is that it does not refer to a commonly known or OSI accepted license. On the linked website I can not find the actual text of "Free for commercial use" license either.

As it stands I have enough doubt over the license and the original source of this icon that I can't accept it. The guidelines also state that this is something we do not want.

My advice is to find a new icon that is expressly licensed under a CC- type license, document the origin and attribution, and then you'll be fine.

**Comment by mahmutelmas06** [comment]
I drow new icon by myself.

So everything should be fine now.


Thank you



Mahmut Elmas


________________________________
Gönderen: Auke Kok <notifications@github.com>
Gönderildi: 22 Kasım 2016 Salı 21:05
Kime: minetest-mods/minetest-mods.github.io
Bilgi: Mahmut Elmas; Author
Konu: Re: [minetest-mods/minetest-mods.github.io] New mod request: commander (#24)


Our guidelines for accepting modules talk about cases like this explicitly, to protect both you and users of your mods.

The problem with "Free for commercial use" is that it does not refer to a commonly known or OSI accepted license. On the linked website I can not find the actual text of "Free for commercial use" license either.

As it stands I have enough doubt over the license and the original source of this icon that I can't accept it. The guidelines also state that this is something we do not want.

My advice is to find a new icon that is expressly licensed under a CC- type license, document the origin and attribution, and then you'll be fine.

-

**Comment by sofar** [comment]
Ok, yes, if you drew it yourself you're good now.

I recommend putting in a separate artwork license statement:

`commander.png is Licensed CC-BY-3.0 by Mahmut Elmas`

Or, at your choice, a different license. MIT is not necessarily a good choice for artwork.

But, that's completely optional.

If you are ready, please initiate a repository transfer to `sofar` using the github settings. I then move the repo through to minetest-mods, and the website will make redirect links and keep everything, including your access, intact.
