### ISSUE TITLE
New mod request: ropes

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#27]
FaceDeer here. I'd like to submit the "ropes" mod to minetest-mods. It's under WTFPL

Repository: https://github.com/FaceDeer/ropes/

This one might be a bit tricky under a strict reading of the rules. It's technically a fork of Bas080's "vines" mod, which can be found here: https://github.com/bas080/vines. However, the rope-related section of that mod was very minimal and riddled with issues. I essentially rewrote the rope stuff from scratch, and then separated it out from the vines stuff to stand on its own. So there's almost nothing from the original mod left in this mod. I tried contacting Bas080 at various points but have never got a response (I first started tinkering with this back in June).

**Comment by sofar** [comment]
Notification to @bas080 - I think it's enough new code / rewrite but I prefer notifying authors that a descendant of their code will remain maintained so they can potentially refer users to the new version.
