### ISSUE TITLE
New mod request: hopper

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#28]
FaceDeer here. I'd like to submit the "hopper" mod to minetest-mod. It's under the MIT license.

Repostiory: https://github.com/FaceDeer/hopper/

This one is possibly contentious, but I was advised to send it in anyway and discuss it here. TenPlus1 is maintaining hopper and I forked it to add a bunch of bugfixes and enhancements, but TenPlus1 declined to take my pull request and I think the fixes are significant. In a nutshell, the version I forked this from doesn't make use of standard Minetest APIs when putting things into or taking things out of node inventories, relying on special-case code to force furnaces to run when fuel is inserted and not properly checking whether item insertion and withdrawal is permitted. A modding API has been added to hopper that allows other mods to add new nodes as sources and targets so I think it's important to handle these things in a robust manner (it's why I made these fixes in the first place).

I also added a bunch of documentation, some user options to allow different texture resolutions and crafting strategies to be selected, and made side-hoppers able to function in any orientation.

**Comment by sofar** [comment]
Notification to @tenplus1 

As per guidelines, we discourage forks. Since tenplus1 is already maintaining a fork, and the original author hasn't been around for a year(or so), this clearly falls under the type of mods we'd encourage to get into minetest-mods.

If @tenplus1 isn't willing or has time to consider pull requests, I'll gladly allow @facedeer to work on his project as part of minetest-mods.

Comments?

**Comment by FaceDeer** [comment]
If it's preferred, I originally mistakenly began work on hoppers using the original jordan4ibanez repository here: https://github.com/FaceDeer/Hoppers/ (I didn't read down the forum thread to discover that tenplus1 had taken over maintaining the mod until I'd done a bunch of work and went back to the thread to announce it). I could port the new API and other subsequent changes that I made back into there, then I'd be forking jordan4ibanez instead of tenplus1 according to the history recorded by git. The end result would be essentially the same code though so I don't think there's any real benefit to that.

**Comment by sofar** [comment]
@tenplus1 hasn't taken over maintenance, he's effectively forked it. As far as I know (and I've asked jordan4ibanez a few times myself) nobody has been designated a maintainer by him.

**Comment by FaceDeer** [comment]
Apologies for the false alarm, I started transferring repositories and then got distracted working on them instead.

**Comment by sofar** [comment]
:+1: go ahead and start the transfer of your branch. I might sever the "fork of" link in the process.

**Comment by FaceDeer** [comment]
Github said the transfer was already in progress. I aborted and restarted it, let me know if you don't see it from your end.

**Comment by sofar** [comment]
I ended up doing a link-free clone, and gave you back the full access to it.

https://github.com/minetest-mods/hopper
