### ISSUE TITLE
New mod request: the Digtron

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#29]
FaceDeer here. I'd like to submit my mod "digtron" to minetest-mods. It's under LGPL 2.1 or later, with CC licenses for the sounds.

Repository: https://github.com/FaceDeer/digtron/

**Comment by sofar** [comment]
:+1:

**Comment by sofar** [comment]
For all these mods that I've approved, please initiate a github repo transfer to user `sofar`. This is the easiest method to migrate all the data.
