### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by mahmutelmas06** [minetest-mods/minetest-mods.github.io#3]
Beverage -  https://forum.minetest.net/viewtopic.php?f=9&t=13601&p=198444#p198444
mahmutelmas06 - Github name
WTFPL code

**Comment by sofar** [comment]
All set up! Nice mod. Glad to see it join minetest-mods.

You may want to adjust forum links and grant more people commit access. Please feel free to submit a ticket here!

https://github.com/minetest-mods/beverage
