### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by NathanSalapat** [minetest-mods/minetest-mods.github.io#30]
I'd like to transfer my drinks mod, https://github.com/NathanSalapat/drinks

**Comment by sofar** [comment]
👍 

As a side note, the textures are horribly out of size - 16px bottle but the barrel is almost 512px?

To start the transfer, do a github transfer to user `sofar`.

**Comment by NathanSalapat** [comment]
The barrel is a mesh object, I could scale down the texture and provide alternate sizes if people would like.

**Comment by sofar** [comment]
Well, it's your mod and code, but I strongly (personally) recommend that you create 16px textures that roughly match stock minetest_game. You won't need more than a 32x32 UVmap to do that I think. Anyway, your choice really.

**Comment by NathanSalapat** [comment]
I'm not very good when it comes to making pixel art for 3d objects, but I'll give it a whirl over the weekend.
