### ISSUE TITLE
New mod request: sounding_line

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#31]
Made another one. :) The sounding line mod: https://github.com/FaceDeer/sounding_line

License: LGPL 2.1+

**Comment by sofar** [comment]
There's nothing really wrong with this mod per se (license is fine etc.) but it's awfully niche, isn't it?

**Comment by FaceDeer** [comment]
Well, yes - that's one of the main reasons why I made it a stand-alone mod. I originally came up with the idea for this while working on the ropes mod but I decided against bundling it with that because a lot of people might not want to have both installed.

Here's my guiding philosophy, perhaps this is a good opportunity for me to run it past you and see how it fits with the bigger picture.

A mod is a basic "atom" of dependency. Things should be bundled together into the same mod if they can't reasonably be separated, either due to a tight dependence on shared code or a tight functional connection (the springs in my dynamic_liquid mod, for example, share no code with the fluid dynamics part but would be completely pointless if installed separately). There's a standard interface that allows the player to enable and disable mods, but there's no standard way of enabling and disabling _parts_ of mods.

When there's a group of mods that fit together well thematically and will often be used together, but that don't strictly depend on each other and may have some members that won't always be desired, that's what a mod pack is for. When there's a group of mods that are specifically selected to synergize with each other and don't make sense to split up, but that are too big to put into one mod together (or are from disparate sources), that's a game (Mars Survive, for example).

I've actually been pondering how to broach this subject over on the Castle mod. Castle has a rope block bundled with it that has the same weaknesses as the version of the rope block that was included in the Vines and Ropes mod (I think they were probably derived from a common root). I'm currently working on making my rope mod work as a drop-in replacement for the Castle rope block and I'm not sure what the proper approach is to that. The Castle rope block shares no code with the rest of the mod, all of its functionality is contained within rope.lua, so this would be simpler if it was a member of a Castle-themed mod pack instead.

**Comment by sofar** [comment]
Alright well, approved. Hit the transfer button when you want. (to sofar)

**Comment by FaceDeer** [comment]
Transfer initiated.

If you like, I could try adding some additional uses that use the same code in different ways. Maybe allow the sounding line node to be tipped on its side to measure distance horizontally as well? I expect the primary use would still be plumbing the scary depths, since one can measure horizontal distances a lot more safely than jumping down an unknown hole, but I could see some use to having a measuring tape as well.
