### ISSUE TITLE
New mod request: edit

### ISSUE THREAD

**Issue by MrRar** [minetest-mods/minetest-mods.github.io#32]
username: MrRar,
mod name: edit,
license: GPLv3

**Comment by sofar** [comment]
Where's the original github? or is this not live yet? Forum link?

**Comment by MrRar** [comment]
Sorry, I should have thought of that. it's https://github.com/mrrar/edit/

**Comment by sofar** [comment]
Code and license are OK. But the artwork seems to be directly copied from windows?

**Comment by MrRar** [comment]
@sofar, indeed. I guess I don't have any legal standing for doing so. I have now switched them to all original artwork.

**Comment by sofar** [comment]
Approved but under 1 condition: Allow me to squash the entire repo to one commit (during the transfer)

-> This allows me to remove the original artwork from the git history.

If you're OK with this, please transfer the repository to `sofar`!

**Comment by MrRar** [comment]
Done.

**Comment by sofar** [comment]
https://github.com/minetest-mods/edit
