### ISSUE TITLE
New mod request: airtanks

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#33]
A cursory search didn't find any straightforward mods for underwater support so I made this: https://github.com/FaceDeer/airtanks/

Name: airtanks
Author: FaceDeer
License: WTFPL

**Comment by sofar** [comment]
Suggestion, please relicense to MIT or X11, or something without profanity. The WTFPL makes it hard for schools to use.

**Comment by sofar** [comment]
Approved otherwise. A relicense and then transfer to `sofar` ?
