### ISSUE TITLE
New mod request: subterrane

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#34]
https://github.com/FaceDeer/subterrane by FaceDeer, a set of utility functions that can be used by other mapgen mods to create large natural underground caverns and decorate them with biome-specific features.

The basic code of this mod started out long ago in https://github.com/paramat/subterrain by Paramat, and was adapted by HeroOfTheWinds for use in his https://github.com/HeroOfTheWinds/minetest-caverealms mod. I have rewritten it extensively, however, turning it into a generic utility mod and adding a bunch of features.

It's currently used by two mapgen mods, https://github.com/FaceDeer/minetest-caverealms (a fork of Caverealms that makes use of subterrane) and https://github.com/FaceDeer/dfcaverns (an attempt to recreate the underground realms of Dwarf Fortress).

Name: Subterrane
Author: FaceDeer
License: WTFPL

**Comment by sofar** [comment]
Suggest relicense to MIT or X11 ish due to wording, again.

**Comment by sofar** [comment]
ok otherwise. relicense and transfer to `sofar` ?

**Comment by FaceDeer** [comment]
It's derived from code that was originally under the WTFPL, but I guess that license does allow relicensing (and anything else TF) so MIT is fine. :)
