### ISSUE TITLE
New mod request: pontoons

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#36]
Just noticed that I forgot to submit this mod back when I first wrote it. It was made to satisfy a request to provide some way of building stuff more easily on the surface of deep bodies of water, and threw in steel pontoons for building on lava as well.

https://github.com/FaceDeer/pontoons

Mod name: Pontoons
Author: FaceDeer
License: MIT

**Comment by sofar** [comment]
You know the drill.

**Comment by FaceDeer** [comment]
Should I preemptively start a transfer when making these requests in the future? I don't want to seem presumptive, in case you choose to respond with "no, stop spamming me with strange things you silly modder" :)

**Comment by sofar** [comment]
No, please always open a ticket first!
