### ISSUE TITLE
New mod request: minetest-mod-mesecons

### ISSUE THREAD

**Issue by Jeija** [minetest-mods/minetest-mods.github.io#37]
I've decided to transfer [minetest-mod-mesecons](https://github.com/Jeija/minetest-mod-mesecons) to the minetest-mods orgnization. Mesecons was started and initially written by me and has received lots of contributions by various developers in the minetest community in the past years. Mesecons code is licensed under the LGPLv3, all textures and other non-source code content is licensed under the CC-BY-SA-3.0.

For now I'd still like to keep [mesecons.net](https://github.com/Jeija/mesecons.net) (both the repository and the website). We also need to make sure to inform [Debian maintainers](https://packages.debian.org/search?keywords=minetest-mod-mesecons) and other packagers about the move to minetest-mods. Minetest-mods should continue to publish [stable releases](https://github.com/Jeija/minetest-mod-mesecons/releases) for those packagers to include in their distributions.

**Comment by sofar** [comment]
Approved

**Comment by sofar** [comment]
Given that mesecons is somewhat large, I'd like to propose using the opportunity to rename the repo to "mesecons" so that the final URL becomes "github.com/minetest-mods/mesecons"

**Comment by sofar** [comment]
This may also be a good time to consider to do what the `castle` mod did - split out all the mods into subtrees, and use a stub `modpack` tree for releases. But for mesecons I won't require that - it's been established in it's current form long enough that I'm fine with it remaining a modpack as it is now.

**Comment by sofar** [comment]
For completeness, the procedure we've been using is to github `transfer` the repository. Since you can't directly transfer from a user to an org, you'll have to transfer to me (`sofar`) instead. I then redirect it through to `minetest-mods`, and afterwards I grant full access back and anyone you'd want to retain access.

**Comment by sofar** [comment]
Just saw your transfer, and I'll accept in a second - are you OK with renaming it to `mesecons` ?

**Comment by sofar** [comment]
I renamed it assuming you're OK with it. 

Note that github will redirect people as long as you don't fork it back to github.com/jeija/minetest-mod-mesecons. If you end up forking again, picking a different name will help to avoid the redirect from getting lost.

Please update the forum post and your website, of course!

**Comment by Jeija** [comment]
Yes, I was okay with renaming it to `mesecons`. I'm also okay with different ways to organize mesecons, e.g. as a mod instead of a modpack. Just always make sure that these changes are compatible with other mods depending on mesecons as well as the mesecons.net documentation. Since quite a lot of mods depend on mesecons, websites link to it etc., it might be easier to just keep it in its current form as a modpack.

**Comment by sofar** [comment]
We'll leave it as is for a bit first, the move is probably more work for most contributors.

Happy hacking!
