### ISSUE TITLE
Official (hosted) Weblate project for minetest-mods

### ISSUE THREAD

**Issue by LNJ2** [minetest-mods/minetest-mods.github.io#39]
Many mods already have i18n support, but it isn't really used, because there are only a few people opening pull requests for new l10ns. An official Weblate project with all mods would really simplify this. And then translators without git knowledge could also get involved.

Contra:
> Currently all mods are using a intllib that is operating server-wide. There is no official way of the Minetest engine to translate mods, this should be implemented and used before we create an official translation project.

Since intllib is using gettext files, also for the future all translations should be compatible with a maybe coming engine sided way for that, so we can already start translating before this API is added, even if it's currently not working for multilingual servers.

**Comment by rubenwardy** [comment]
:+1:

@kaeza

**Comment by kaeza** [comment]
@sofar also entertained this idea and I fully support it.

I have been tinkering a bit with a local Weblate install using components for mods. Would this be the right approach? The hosted Weblate plan for open source projects only allows [up to 25 components](https://weblate.org/es/hosting/), so there will be a need to raise funds for a paid plan or alternative hosting.

**Comment by kaeza** [comment]
@rubenwardy The Minetest Mods app can also go in, methinks.

**Comment by sofar** [comment]
No. (*)

(*) I want to be clear that minetest-mods does not advocate how projects should be run by the project owners. I'm cautiously positive about mod owners and translators improving translation progress, but I want to be absolutely sure that this isn't perceived as an invasive way that makes mod writers lose control over merging their requests. So if we do anything like this, it needs to be opt-in and there should be a way for mod owners to reject i18n pull requests. Having translations in your project is a significant time sink, especially for the larger project - we really want to be very, very careful with this.

**Comment by LNJ2** [comment]
@sofar We don't want to make this a 'have-to', it's just for those mod authors who _want_ i18n support, it should just simplify the work of translators, so more translations will be made.
I just want to have one official minetest-mods weblate project, so not every mod has its own (that really makes no sense for small mods that maybe have only 10 strings or less).

**Comment by sofar** [comment]
25 is pretty low. I'm also not inclined to start hosting our own weblate and 200$ per year is really steep.

This is really not very compelling. Having a free weblate per project would be more attractive at this point.

**Comment by LNJ2** [comment]
I opened a hosting request for my MTG i18n mod and asked if they were able to change the limit for us.

**Comment by nijel** [comment]
I see no problem in raising the limit here and having all under Minetest project. The i18n mod is now there: https://hosted.weblate.org/projects/minetest/mtg_i18n/

The limit is really soft to make people think whether think they want to host really makes sense to split into so many components.

The free hosting still costs us some money, so if you're in position to do that, you are welcome to support us in providing this service for free:

https://weblate.org/donate/

**Comment by LNJ2** [comment]
@nijel Oh, that is very nice! Thank you very much. :+1:

**Comment by LNJ2** [comment]
@nijel There is just one problem: I don't have git access to my mods on weblate. So I can't update the checkout on weblate.

**Comment by nijel** [comment]
I've just added you. Also it's better to automate this than doing manually, see https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github
