### ISSUE TITLE
New mod request: monoidal_effects

### ISSUE THREAD

**Issue by raymoo** [minetest-mods/minetest-mods.github.io#4]
I would like monoidal_effects(https://github.com/raymoo/monoidal_effects) to be added to minetest-mods.

It is an effect framework similar to playereffects, with the main difference being that it supports effects that can combine to create a cumulative effect while multiple are active.

It is a work in progress, but I have confirmed that one very small test case (applying multiple speed modifiers) works. To further test it, I will add a standard suite of monoids, and also try to incorporate it into the magical_realm modpack.

LICENSE: Apache v2
Github Name: raymoo

**Comment by sofar** [comment]
Done, and given you access. Mod looks like a good start for a solid framework. Hope you can build it out to something great.

Cheers.
