### ISSUE TITLE
New mod request: throwing

### ISSUE THREAD

**Issue by paly2** [minetest-mods/minetest-mods.github.io#40]
Hello, sorry for my bad English,
There is no throwing mod available in this organization, so I suggest you to transfer my implementation of throwing.

GitHub repo: https://github.com/Mynetest/throwing
Forum Topic: https://forum.minetest.net/viewtopic.php?f=11&t=16365

The code is currently licensed under Mozilla Public License 2.0. Textures were made by PilzAdam for his own throwing mod, and they are licensed under WTFPL.

**Comment by sofar** [comment]
Please add a description.txt,

**Comment by sofar** [comment]
Approved. Transfer the repo to `sofar` please.

**Comment by paly2** [comment]
Thanks :-) Done
Please note that the mod has changed since this PR has been open. Now, https://github.com/MT-Eurythmia/throwing is just an API. https://github.com/paly2/throwing_arrows is needed to register the arrows and the bows. I transferred both.
You may prefer to merge them into a modpack before transferring to the `minetest-mods` organization?

**Comment by sofar** [comment]
no modpacks! we prefer separate mods (by a very large margin)
