### ISSUE TITLE
New mod request: Avenues

### ISSUE THREAD

**Issue by MrRar** [minetest-mods/minetest-mods.github.io#41]
url: https://github.com/mrrar/avenues
license: CC0

**Comment by sofar** [comment]
some of your code is based on pipeworks code, which is lgpl-2.1. Your code therefore can not be CC0, this is a license violation.

A simple solution would be to license your code under the LGPL-2.1 and properly attribute the code that is part of pipeworks (quote the copyright notices).

I'm also not a fan of the way you maintain the repo. Uploading new files isn't how you should work with git.

**Comment by sofar** [comment]
The above issues need fixing before this can be accepted. Sorry for the delay, I was not receiving notifications somehow.

**Comment by sofar** [comment]
No response. Closing until requested actions are taken and item is resubmitted.
