### ISSUE TITLE
New mod request: Simplecrafting_lib

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#42]
Github: https://github.com/FaceDeer/simplecrafting_lib

This mod provides a new way of handling crafting, with https://github.com/FaceDeer/crafting as an example of a mod that makes use of it. Bits of it were originally developed by Qwertymine3 (in https://github.com/Qwertymine/crafting) but I've reworked it very extensively since then and turned it into a utility mod that can be used by many other mods in various ways.

It's under the MIT license.

**Comment by sofar** [comment]
`description.txt` missing

**Comment by sofar** [comment]
I can't find the license in the readme, would be good to include that there as well.

**Comment by sofar** [comment]
otherwise OK, please fix the issues and transfer to `sofar`
