### ISSUE TITLE
New mod request: item_drop

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/minetest-mods.github.io#43]
[PilzAdam](https://github.com/PilzAdam)'s [item_drop](https://github.com/PilzAdam/item_drop) is starting to have deprecated calls in it and PRs aren't being evaluated, accepted nor rejected. Since the author is unresponsive I suggest forking. It's too popular and too good to fall into oblivion. The sprawl of forks already existing is just a mess. Let's maintain it together!

https://github.com/tacotexmex/item_drop . License is WTFPL.

**Comment by tacotexmex** [comment]
Is there anything wrong with the mod or it's licensing?

**Comment by sofar** [comment]
I'll make you a deal: I'll approve this and we'll initialize the repo from scratch to avoid the fork. However, I'd like you to do the following things:

- relicense to MIT
- add description.txt, depends.txt, mod.conf and possibly other missing mod files that should be there (screenshot would be nice)
- there are a few alternatives out there, it would be good to contact the people who have made alternatives and pull them in so we can make one decent item_drop mod instead of 3 different ones.

deal?

**Comment by tacotexmex** [comment]
Your requirements are reasonable, I'll sort them out. I wonder about the licensing however. I've learnt that it's best if my work is licensed the same as Minetest, so I've made everything in LGPL 2.1 + CC-BY-3.0. Why MIT and not LGPL? I don't care very much either way, I just want to learn the reason.

**Comment by sofar** [comment]
LGPL is OK too. You can go from WTFPL to MIT and from MIT to LGPL, so it's all good. You can't go from LGPL to MIT however, so choosing MIT is like the simplest step you can take to get away from WTFPL.

**Comment by tacotexmex** [comment]
Oh okay, I'll just commit two license changes then, MIT first and LGPL second. 👍

**Comment by DS-Minetest** [comment]
>there are a few alternatives out there, it would be good to contact the people who have made alternatives and pull them in so we can make one decent item_drop mod instead of 3 different ones.

All other item_drop mods that I've found with Krock's search and have a github repo:
- https://github.com/PilzAdam/item_drop (old, dev is away, maybe look to forks)
- https://github.com/jordan4ibanez/item_drop @jordan4ibanez
- https://github.com/HybridDog/item_drop (afaik it works well) @HybridDog
- https://github.com/taikedz/everamzah-item_drop_new (dev is away)

**Comment by tacotexmex** [comment]
Jordan's doesn't work very well in multiplayer, along with some other bugs. Not sure if there's any new features there.

HybridDog's might have some improvements but I'm not sure they've been written with upstream merging in mind.

everamzah's I haven't vetted.

**Comment by tacotexmex** [comment]
Apart from a screenshot which can be added later, the mod is ready @sofar.

**Comment by HybridDog** [comment]
It's a small mod, l recommend you to rewrite it from scratch.

**Comment by sofar** [comment]
I did a clean clone of your repo and put that in minetest-mods/item_drop as to sever the "fork" relationship that otherwise github creates.

**Comment by tacotexmex** [comment]
Hey @sofar, can we redo it so that _I_ sever the fork relationsship instead? That way, cloners of my original repo will be automatically redirected to the new URL when pulling.

**Comment by tacotexmex** [comment]
> It's a small mod, l recommend you to rewrite it from scratch.

I can't.

**Comment by HybridDog** [comment]
You already changed so much that the code looks like from another mod.

**Comment by tacotexmex** [comment]
Nope. 🙂  Apart from integrating nerzhul's optimization PR and updating deprecated methods I haven't touched the code of the core mechanic at all.

**Comment by HybridDog** [comment]
das

**Comment by HybridDog** [comment]
there's not much core machanic, it's just item picking and dropping

**Comment by HybridDog** [comment]
ࡧ

**Comment by tacotexmex** [comment]
Yes.

**Comment by tacotexmex** [comment]
@sofar, my repo is now set up as regular source repo. Please remove the minetest-mods repo and use this instead. This way existing cloners won't experience breakage.

**Comment by sofar** [comment]
no worries, done.

**Comment by HybridDog** [comment]
l've shortened the code a little bit (untested): https://github.com/HybridDog/item_drop/commit/a9752e328a45fb09f59ef2f66f6cf4c51b07d39d?w=1
BTW: Since https://github.com/minetest/minetest/commit/e09c7fceaa93ad3d7d85f657df0663f6efc70281 you don't need to test if itemstring is "" l think.

**Comment by HybridDog** [comment]
l've redone my changes for a cleaner history: https://github.com/HybridDog/item_drop/commits/master

**Comment by tacotexmex** [comment]
Nice work @HybridDog, I'll check it out. Let's continue in the issue tracker of item_drop!

**Comment by sofar** [comment]
@HybridDog I'll give you push access to item_drop as well, feel free to do incremental cleanups and take care of the code with us.

**Comment by HybridDog** [comment]
thanks

**Comment by jordan4ibanez** [comment]
Okay I'll redo mine

**Comment by tacotexmex** [comment]
@jordan4ibanez You don't want to contribute to optimize this item_drop then? :slightly_smiling_face:
