### ISSUE TITLE
New mod request:skinsdb

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#44]
I like to see the skinsdb in minetest-mods. The "master" only, not the "mod_with_skins" branch. As I started searching for the right skins mod I was not able to select the right fork so I started a new one

https://github.com/bell07/minetest-skinsdb

**Comment by sofar** [comment]
@smalljoker

**Comment by sofar** [comment]
@dmonty2

**Comment by sofar** [comment]
Long trail of forks. People interested in maintaining a common version in minetest-mods? It would help to reduce the fork mess :)

**Comment by SmallJoker** [comment]
Sure, why not?

**Comment by SmallJoker** [comment]
BUMP. @sofar, @rubenwardy
Bell and me would be interested in getting this mod into minetest-mods. Contributing isn't a problem for the other modders who forked this repository if there are members who would like to maintain the project. I could be a volunteer, if it's desired.

**Comment by rubenwardy** [comment]
fine by me

**Comment by sofar** [comment]
Transfer to me so I can move it through.

**Comment by sofar** [comment]
https://github.com/minetest-mods/skinsdb

I severed the folkage, and changed name to `skinsdb` as per naming conventions.
