### ISSUE TITLE
New mod request: ccompass

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#45]
The ccompass is a minetest-mods candidate:

https://github.com/bell07/minetest-ccompass

**Comment by sofar** [comment]
while it is technically a fork (is echo's version on github?) I think this is OK.

- relicense to MIT please
- add description.txt

then transfer to `sofar` please.

**Comment by bell07** [comment]
This mod is based on echo's version. I upload them to github at initial commit (before it was not on github). The "legacy" branch still contains the echo's mod with some enhancements/updates before I decided for "calibration" feature. I renamed the mod because of removal other target determinations by sethome and bed.

The new version contains new textures by @tacotexmex

Relicensed in https://github.com/bell07/minetest-ccompass/commit/823bced336438b5da5c12ef9b48b935a10cdba86, please check if it is right, I am not license guru.
