### ISSUE TITLE
New mod request:woodcutting

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#46]
The woodcutting in minetest-mods?

https://github.com/bell07/minetest-woodcutting

**Comment by sofar** [comment]
- add `description.txt`

OK otherwise. Readme could use some spelling/grammar fixes :)

approved. transfer to `sofar` when fixed up the above comments.

**Comment by bell07** [comment]
description.txt added, maybe needs some spelling/grammar check too :-( I never learned English in the school
Transfer requested
