### ISSUE TITLE
Add auto-updating mod list, rather than requiring a commit in this repo

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/minetest-mods.github.io#48]
From http://minetest-mods.github.io/mods.html :
> Minetest-mods hosts 102 mods.

But it doesn't, it currently hosts 151 mods. 49 isn't listed on the web page.

**Comment by rubenwardy** [comment]
There needs to be a commit to the repo for it to update, iirc

**Comment by rubenwardy** [comment]
Done

**Comment by sofar** [comment]
:+1:

**Comment by Ekdohibs** [comment]
Couldn't we have some way to forcing rebuild? This could maybe be done with a bot that creates a dummy commit, pushes it, then removes it and force-pushes again (to keep a clean history) each time there is a new repo under minetest-mods/ -- but a cleaner solution would be nice.
