### ISSUE TITLE
avatar-biome

### ISSUE THREAD

**Issue by Robi99** [minetest-mods/minetest-mods.github.io#49]
Hi, I found and old minetest game inspired by avatar, what looks good I think. I modified it to a biome mod, what works with recent mods.
I would like to add this to minetest.mods.
Thank you.

[avatarmods.zip](https://github.com/minetest-mods/minetest-mods.github.io/files/1540768/avatarmods.zip)

**Comment by sofar** [comment]
Please post a link to the original github (or other git) sources.

**Comment by Robi99** [comment]
https://github.com/tony-ka/minetest-Avatar
or forum subgame release
https://forum.minetest.net/viewtopic.php?t=2845

**Comment by sofar** [comment]
One thing to note is that this organization is called `minetest-mods` not `minetest-subgames`. We prefer to host individual mods that meet certain criteria, and not modpacks or subgames.

If parts of the mods in these subgames are worth maintaining, we can decide on a case-by-case basis. Otherwise, I think I will close this request.

**Comment by Robi99** [comment]
I converted the subgame features into my mod. It's just a mod, not subgame any more. It just add a biome to any world. As per settings it will be the only biome or just one biome among existings ones.
It is modpack becuase I wanted to add the orginal subgameplants  as well. But can be separated.

**Comment by sofar** [comment]
Games are per definition not something we accept. And I've been very strict about modpacks. The only modpacks I've allowed are things that are incredibly widely used and legacy, like mesecons/technic.

I can't give approval until I see the project is a mod. What I see right now linked is a game/modpack, so, either you should consider making a mod for the mapgen part and a mod for the plant part, which would be acceptable IMHO (need to check the other things like license of course), or find another way to make it a mod.
