### ISSUE TITLE
carpets mod

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#55]
I have 2x carpets mods, one of them I like to see in minetest-mods, the second should be deprecated. Which mod should have which future is not decised:

https://github.com/bell07/minetest-carpets-legacy
By @Rui-Minetest, he transferred the ownership to me after I done my mod.
It is a modpack with hard-coded material-node-lists for default, nyancat and wool carpets

https://github.com/bell07/minetest-carpets
Based on Rui- mod but with generic material lists. It was one of my first mods. The depends.txt is used, the listed mods are analyzed which items could be material for an carpet. So additional carpets can be enabled by editing the depends.txt file.

In the meantime I am away from idea "as much items as possible with all shapes for all textures mods" and do not use both mods byself.
Which of the moth mods can be applied to the minetest-mods and which one should be deleted?

**Comment by sofar** [comment]
Neither.

First, we should absolutely not do a modpack for this.

Second, the arbitrary expansion type mods that add a virtually unlimited amount of nodes are absolutely harmful and only something special servers should ever use (and they're dangerous for those due to lots of nodes).

So, I'd just like to see a simple carpet API with only a standard set of wool carpets, only. Kind of like walls and xpanes. That would be reasonable, and even desirable, I think.

**Comment by bell07** [comment]
The "Second" is not fully true. The mod uses only nodes defined in depends.txt So if I write the "wool" only to the depends txt and remove all other listed mods, you get only wool carpets as requested. The value of my mod version is the framework to analyze the depends.txt and filter the carpet-compatible material items.

**Comment by bell07** [comment]
Please have a look to my "minetest_mods" branch at https://github.com/bell07/minetest-carpets/tree/minetest_mods

I did code cleanup, removed the settings and woodo, now it is the API only and wool carpets optional.

The Woodo I plan to move to the https://github.com/bell07/minetest-customnode including the carpet-API support, so if anyone needs the generic carpets registration he can use the customnode (if implemented)

**Comment by bell07** [comment]
now magic moved to customnode and cleanup moved to master. Pls. accept https://github.com/bell07/minetest-carpets

**Comment by sofar** [comment]
I'm totally OK with the code as it is, and will accept this, but there's no license statement anywhere?

while you fix that, please add a `screenshot.jpg` and a `description.txt`. Then it should be good to go.

**Comment by bell07** [comment]
The license is WTFPL, but we can re-license them if @Rui-Minetest (initial author) does not have objection.
I'll add the description.txt and screenshot in the evening

**Comment by Rui-Minetest** [comment]
I have no objection.

**Comment by bell07** [comment]
description.txt, screenshot.png added and README.md updated.
License still WTFPL. Which one should be used?

**Comment by sofar** [comment]
ISC or MIT are good baseline licenses. Alternatively, LGPL-2.1+.

**Comment by bell07** [comment]
New license is LGPL-2.1+ like the minetest itself. I requested the transfer to you @sofar

**Comment by sofar** [comment]
renamed to `carpets`

**Comment by bell07** [comment]
Thanks. Updated forum topic: https://forum.minetest.net/viewtopic.php?t=15459
