### ISSUE TITLE
Frozenenergy

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#57]
The frozenenergy is a candidate for minetest-mods:

https://github.com/bell07/minetest-frozenenergy
https://forum.minetest.net/viewtopic.php?f=11&t=17745

**Comment by sofar** [comment]
OK with me, I just wonder if it would be better to make water just freeze if it's adjacent to 3 or more ice nodes. Since ice can be placed, that would also make it farmable and would avoid the need for a "speciality" item entirely.

**Comment by bell07** [comment]
This mod I wrote primary to play on singlenode worlds like Unternull. The issue with freeze water by ice is to obtain the first 3 ice nodes. The frozenenergy node is crafteable by other available materials and freeze max. 26 nodes around. Using just 1x node the ice farming needs patience.
