### ISSUE TITLE
Minetest-technic mods

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#58]
The mods from https://github.com/minetest-technic seems to be not maintained anymore. PR's and issues remains untouched. Maybe some of them should be forked to minetest-mods?
I like and use the "mese_crystals" from this mods collection

- [ ] mese_crystals - still uptodate - small correction (fix leaked global) as pull request exists
- [ ] ~~item_tweaks~~ - exists in many shapes already, would likely be duplicate and out of date
- [X] stargate - https://github.com/minetest-mods/stargate
- [ ] ~~datastorage~~ - outdated - should not be used anymore
- [ ] ~~technic_game~~ - is a game - not a mod
- [ ] ~~technic_game_2~~ - is a game - not a mod

**Comment by sofar** [comment]
@nore and me talked this over. I think we didn't care much about the remaining mods, but if you do, we can do this. @nore can transfer `mese_crystals` and perhaps assign a reasonable license to it (ISC?).

**Comment by bell07** [comment]
- [ ] mese_crystals - still uptodate - small correction (fix leaked global) as pull request exists
- [ ] item_tweaks - not really understand what the mod does - but maybe still usefull?
- [ ] stargate - stores data to worlddir files. Needs update to modmeta or playermeta at the first
- [ ] ~~datastorage~~ - outdated - should not be used anymore
- [ ] ~~technic_game~~ - is a game - not a mod
- [ ] ~~technic_game_2~~ - is a game - not a mod

**Comment by sofar** [comment]
stargate is already in minetest-mods.
item_tweaks exists in many shapes already, would likely be duplicate and out of date.

**Comment by bell07** [comment]
Ok, then I like to see the remaining mese_crystals in minetest-mods. 
You can add me to maintainers

**Comment by sofar** [comment]
Sorry for slow (I suck at prioritizing).

`mese_crystals` contains no license info or attribution. I'm going to leave it where it is for that reason. If someone wants to implement a version that does the same and has correct and verifyable attribution, then that is fine and we'll consider including that version.

**Comment by sofar** [comment]
Closing this as we've now come to a conclusion on all the mods listed.
