### ISSUE TITLE
jumping

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#59]
I recoverded changes of @endev15 for the jumping mod, but the upstream seems to be dead, does not accept the changes.
See https://github.com/Jeija/minetest-mod-jumping/pull/5
 
So please add the fork https://github.com/bell07/minetest-jumping to the minetest-mods

**Comment by sofar** [comment]
@jeija I assume you're OK with the transfer, but it's best if you initiate the transfer to retain links etc.

**Comment by sofar** [comment]
from minetest-mods perspective this is approved at least, but lets' try to get it transferred instead of cloning.

I'd also want to de-modpack it to a normal mod.

**Comment by Jeija** [comment]
Okay, I will initiate a transfer of https://github.com/Jeija/minetest-mod-jumping to minetest-mods. You can then commit @bell07's changes to the transferred repository.

**Comment by sofar** [comment]
Done, thanks. @bell07 if you have any commits you want (I cleaned it up a bit) you may want to rebase and merge them. Let me know if you want push access.
