### ISSUE TITLE
"Minetest Mods Team" and "Minetest" use the same organization picture

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/minetest-mods.github.io#67]
I noticed that both Organizations use the same image:
![2018-10-02-163939_1920x1056_scrot](https://user-images.githubusercontent.com/3192173/46355877-f20f0c80-c661-11e8-856b-ebe83fae1418.png)
The left one is minetest and the right one is minetest-mods.
A different image would make distinguishing the two easier when viewing someone's profile on github. Mods can be used to change the map, so maybe this can be reflected in the image, a simple example:
![otu](https://user-images.githubusercontent.com/3192173/46356584-54b4d800-c663-11e8-95bd-94cec0407fc4.png)

**Comment by sofar** [comment]
I made a new image. It's a modified version of the original logo, but emphasizing the "change it" philosophy. If someone wants to improve on it, I'd be happy to let them at it.

**Comment by HybridDog** [comment]
thanks.
