### ISSUE TITLE
New mod request: ancientrunes

### ISSUE THREAD

**Issue by spixi** [minetest-mods/minetest-mods.github.io#68]
https://github.com/spixi/ancientrunes
Code: Apache 2.0
Textures: OFL 1.1 and CC BY-SA 3.0

**Comment by sofar** [comment]
Yeah, looks nice. Approved.

To start, initiate a github transfer to `sofar`. Then I move it through into minetest-mods. Please ping me when you do so I can handle the transfer right away.
