### ISSUE TITLE
New mod request: mapgen_helper

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#69]
I've been doing a major rewrite of the minetest-mods mod "subterrane" and in the process I made it depend on this mod, [mapgen_helper](https://github.com/FaceDeer/mapgen_helper), where I've put a bunch of general-purpose mapgen code that I plan to reuse in other contexts as well. Before I merge my rewrite of subterrane back into master I'd like to put mapgen_helper into the minetest-mods project as well to ensure that subterrane's dependencies can always be satisfied.

* Mod name: mapgen_helper
* Author: FaceDeer
* License: MIT license, except for two files (voxelarea_iterator.lua and place_schematic.lua) that were derived from Minetest source code and are therefore under LGPL 2.1. Those files have headers inside them indicating their specific licenses and the exceptions are mentioned in the main license file.

**Comment by sofar** [comment]
No problem
