### ISSUE TITLE
New mod request: cake

### ISSUE THREAD

**Issue by MrIbby** [minetest-mods/minetest-mods.github.io#7]
https://github.com/MrIbby/cake
Code: MIT
Textures (by rubenwardy): CC BY-SA 4.0

**Comment by sofar** [comment]
Nice.

Please initiate a "transfer" of your cake repo to "sofar". This will allow me to move it into minetest-mods, and it preserves all the attributes.

https://help.github.com/articles/transferring-a-repository/

**Comment by MrIbby** [comment]
Done.

**Comment by sofar** [comment]
Transfer finished.
