### ISSUE TITLE
New mod request: radiant damage

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#70]
* Mod name: [radiant_damage](https://github.com/FaceDeer/radiant_damage)
* Author: FaceDeer
* License: MIT

I just noticed that I hadn't submitted this mod to minetest-mods either. It's a mod that's meant primarily as a library for adding damage caused by simply being near a node type, but which has some presets available for heat damage from fires and radiation damage from mese.

The mod doesn't use ABMs, and makes use of Minetest 5.0's raycasting when it's available (falling back to simpler methods if run with 0.4.16)

**Comment by sofar** [comment]
Looks good!
