### ISSUE TITLE
New mod request: gauges

### ISSUE THREAD

**Issue by Calinou** [minetest-mods/minetest-mods.github.io#73]
I'd like to move [Calinou/gauges](https://github.com/Calinou/gauges) to the minetest-mods organization :slightly_smiling_face:

**Comment by sofar** [comment]
Accepted. I would however encourage you to switch from CC0 to CC-BY-4.0. Other than that, it's OK.

**Comment by Calinou** [comment]
@sofar How can I transfer the repository? I don't have permission to do it.
