### ISSUE TITLE
It's time to say goodby - my mods

### ISSUE THREAD

**Issue by bell07** [minetest-mods/minetest-mods.github.io#74]
All good things have an end sometime. I had a lot of fun playing and hacking the minetest, and learned a new language "lua". Thank you to all who supported me and was patient with my sometimes ill-conceived Ideas and improvements.

I do not play the game because of 
![image](https://user-images.githubusercontent.com/4731334/55657243-df84b400-57f9-11e9-95c5-f8cf0b84ed68.png)
Since I realized I can change all in modding I do not see the ingame world, but nodes, abm's entities, timers, ..
Now my both childs gets lost the interest on the game too so I lost my "tester" and the last reason to stay with minetest.
 
I do not like to trow away or leave unmaintained all my coding so I ask in this "Issue" what of them could be transferred to minetest-mods.

My leave is not a hard break, I still read the notification mails and maybe write some lua lines, but no own initiative.

## My mods

name | description
-- | --
[smart_sfinv](https://github.com/bell07/minetest-smart_sfinv) | Minetest smart sfinv inventory enhancements - Modpack with different tweak mods

## Forks with changes not accepted by upstream
name | description | My change | Fork
-- | -- | -- | --
[mese_crystals](https://github.com/bell07/minetest-mese_crystals) | | Transfer to minetest-mods rejected because of no license | minetest-technic/mese_crystals
[unternull](https://github.com/bell07/minetest-unternull) | modpack for nodetest - infinite ocean | Different adjustments to be more compatible with minetest game and whynot game | CasimirKaPazi/unternull 
[basic_houses](https://github.com/bell07/basic_houses) |spawn random houses on flat places on the map | Experimental perlin like village placement logic | Sokomine/basic_houses
~~[plasticbox](https://github.com/bell07/minetest-plasticbox)~~ | Plastic Box Mod for Minetest | *change merged to https://github.com/sbrl/plasticbox* | cheapie/plasticbox

## Transfer request approved
name | description | Note | Original fork
-- | -- | -- | --
[mtfoods](https://github.com/bell07/mtfoods) | Food Mod for Minetest | small bugfix, but upstream seems to be dead | Philipbenr/mtfoods
[compost](https://github.com/bell07/minetest-compost) | A compost mod for minetest. | Implemented rare vegetables gifts, useable in singlenode survival world | CasimirKaPazi/compost 
[schemlib](https://github.com/bell07/minetest-schemlib) | A library to handle Minetest Schematics data
[townchest](https://github.com/bell07/minetest-townchest) | A building chest for schemlib - load and place buildings
[schemlib_builder_npcf](https://github.com/bell07/minetest-schemlib_builder_npcf) | Builder NPC that works together and can build own or townchest buildings
[smart_inventory](https://github.com/bell07/minetest-smart_inventory) | Minetest inventory with focus on very much items (smarfs based)
[startanode](https://github.com/bell07/minetest-startanode) | Per-player spawnpoint for singlenode worlds
[customnode](https://github.com/bell07/minetest-customnode) | A framework mod for easy nodes definitions
[orecutting](https://github.com/bell07/minetest-orecutting) | Use sneak key in minetest to faster collect ores. Like minetest-mods/woodcutting, but for ores
[doc_reveal_chest](https://github.com/bell07/minetest-doc_reveal_chest) | doc_items enhancement - Reveal all items in a chest on open
[craftguide_reveal](https://github.com/bell07/minetest_craftguide_reveal) | use wuzzy's doc_items reveal system for minetest-mods/craftguide
[meseor](https://github.com/bell07/minetest-meseor) | | | Upstream is deleted

## My mods already in minetest-mods
name | description | Note
-- | -- | --
ccompass | Calibrated compass | With teleportation - punch mese
skinsdb | Player skins manager. | Should be replaced by skinsdb5 in player_api_modpack
qa_block | Developer tool. | Adhoc lua code
wielded_light | Light up the torch or ther wielded items | With API to get any entity thing shining
frozenenergy | Get ice farmeable. Freeze water around the block. | 
subspacewalker | Go trough stone and dirt and find ores | 
carperts | Just some carpets | with API

## WIP mods I continue to accompany
name | description | Note
-- | -- | --
[player_api_modpack](https://github.com/bell07/minetest-player_api_modpack) | Minetest modpack for mods around player_api enhancements in https://github.com/minetest/minetest_game/pull/2122 | Already in whynot game
[whynot_game](https://github.com/bell07/minetest-game-whynot) | Minetest game in minetest mods collection style | I plan still run the update scripts and look on proposed changes
[whynot_compat](https://github.com/bell07/minetest-whynot_compat) | A minetest mod that should not be | Misc compatibility fixes to get mods working together in whynot game
[schemlib_mg](https://github.com/bell07/minetest-schemlib_mg) | Place buildings on mapgen using schemlib. Unsure if compatible to the latest schemlib version. Not finished work.

**Comment by sofar** [comment]
Thanks, I'll go and make some time and review everything and come up with the best solution for each of them - stay tuned.

**Comment by b3u** [comment]
I'd be happy to take over some. namely, skinsdb and wielded light.

**Comment by sofar** [comment]
great! I still haven't found the time for setting up a full audit and scheduling a migration yet, but it helps if people are ready to lend a hand already. stay tuned.

**Comment by bell07** [comment]
Added list of mods already in minetest-mods

**Comment by sofar** [comment]
minetest-schemlib_mg is lacking license info. OK if you can assign a reasonable license to it, though.

**Comment by sofar** [comment]
minetest-smart_sfinv is a modpack. We'll need to decide whether we keep it together as modpack (and make it an exception) or consider breaking it into separate mods (you can still release a modpack to contentdb manually for instance).

**Comment by sofar** [comment]
minetest_craftguide_reveal needs license and some metadata - there's no README even.

**Comment by sofar** [comment]
These are all OK and approved:
```
schemlib
townchest
schemlib_builder_npcf
smart_inventory
startanode
customnode
orecutting
doc_reveal_chest
```

Transfer them to `sofar` so I can transfer them through.

**Comment by sofar** [comment]
`compost` is approved.
`meseor` needs relicensing to something not `WTFPL` please, but OK otherwise.

**Comment by sofar** [comment]
`unternull` is a modpack - again, split up or not?

**Comment by sofar** [comment]
`mtfoods` is fine, approved.

**Comment by bell07** [comment]
Transfers requested for approved mods. First post updated.
- minetest-schemlib_mg needs more overwork. Unsure if compatible to the latest schemlib. => Move it to WIP mods list. Maybe I find some time to play with "Matrix" again 

- minetest-smart_sfinv is a modpack. My decision was "All-in-one mod" or "Modular in Modpack". I decided to be modular. Each mod is small, most of them depends on the "smart_sfinv_api". So I prefer to keep it as modpack.

- minetest_craftguide_reveal, meseor: I'll check which license should be right one for this mods.

- unternull: @CasimirKaPazi is owner of the mod / idea. He did some changes on his fork, so the upstream is not dead. My fork is WIP again, needs to be adjusted to match the upstream. @CasimirKaPazi, any chance to get my changes to your fork? I prefer to split the modpack and move the 3x mods to the minetest-mods. At least the crushingfurnace does have already long forking history...

**Comment by bell07** [comment]
Requested transfer for minetest_craftguide_reveal and meseor to @sofar

Is modpack exception for smart_sfinv ok? IT does only sense to break down to mods if anyone merges smart_sfinv_api enhancement spots to the sfinv. Otherwise the mods are not useable independently.

**Comment by sofar** [comment]
> Is modpack exception for smart_sfinv ok?

Tempted to make an exception for this

> Otherwise the mods are not useable independently

That's never a reason, though. There's nothing wrong with one mod requiring another, even if only installing the one mod gives no effective capabilities.

**Comment by bell07** [comment]
mese_crystals: Can we transfer the mod to minetest-mods too? Which license did 
RealBadAngel usually used (code and textures)?

smart_sfinv_api: Forgotton to say: the modpack contains a fork of @rubenwardy 's sfinv_buttons ([Original mod](https://gist.githubusercontent.com/rubenwardy/10074b66bd6e409c72c3ad0f79f5771a/raw/47389bbf0dc6badd79362361d0592053add7ceab/init.lua)) ported to the smart_sfinv_api. I do not know how to deal with license. If the modpack is splitted to mods, thay may confusion about original and fork. Let me know if I can setup transfer or if still something missed.

**Comment by sofar** [comment]
> mese_crystals: Can we transfer the mod to minetest-mods too? Which license did RealBadAngel usually used (code and textures)?

I'd like to stay away from that. "Assuming a license" is generally not OK, and I'm going to err on the side of caution here. I also don't think that due to the simplicity of the mod, there would be any issue with someone making a clean implementation with a reasonable license and making that supersede it.

**Comment by bell07** [comment]
Requested the transfer for smart_sfinv modpack. If you like (and have time), you can split them to single mods after transfer

**Comment by sofar** [comment]
Thanks @bell07. May we meet again.
