### ISSUE TITLE
stained_glass by andersje

### ISSUE THREAD

**Issue by sofar** [minetest-mods/minetest-mods.github.io#79]
I was requested to consider: https://github.com/andersje/stained_glass for inclusion in minetest-mods.

@andersje - are you interested in this?

**Comment by andersje** [comment]
Yes, please!   :)

**Comment by sofar** [comment]
@andersje - easiest way to do this is for you to transfer the repo to `sofar` - then I will move it through. This makes sure that people going to the old location will get an automatic redirect to the new location. You can then later re-fork if you need, of course. You also retain access during this process.

**Comment by sofar** [comment]
ping @andersje, please read above instructions if you're ready to proceed
