### ISSUE TITLE
New mod request: global_exchange

### ISSUE THREAD

**Issue by raymoo** [minetest-mods/minetest-mods.github.io#8]
This guy: https://github.com/raymoo/global_exchange
License: GPLv3+

**Comment by sofar** [comment]
Can you transfer the repo to 'sofar'? then I can transfer it through to 'minetest-mods'. Directly won't work.

**Comment by raymoo** [comment]
Ok, done

**Comment by sofar** [comment]
And moved to minetest-mods!
