### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by Niwla23** [minetest-mods/minetest-mods.github.io#80]
plot_system should be added.
its written by TalkLounge, but he didnt wanted to add it here. He started to make a rewrite but has only done the mapgen. Now he wants to leave MT. i forked the project on gitlab:

https://gitlab.com/Niwla23/plot_system/ 
-- nothing changed, just renamed the init.dev.lua to init.lua and deleted the old stuff.

Original Repo:

https://github.com/TalkLounge/plot_system

**Note: the new mod is only in depends.txt and init.dev.lua**
The License seems to allow forks, so i see no problem in adding it here.

**Comment by rubenwardy** [comment]
Please note that this is proprietary software, which is discouraged but not banned from `minetest-mods`

**Comment by Niwla23** [comment]
Which license do you prefer? @rubenwardy Maybe i can talk about that with TalkLounge

**Comment by Niwla23** [comment]
and why is it proprietary?

**Comment by sofar** [comment]
This is up to @talklounge to contribute, and it would need to be relicensed.

@talklounge can respond. If they don't I'll close this. You will not be able to relicense without their permission anyway.

**Comment by sofar** [comment]
Considering @talklounge just did a commit 13 hours ago, I don't think it's abandoned.

**Comment by Niwla23** [comment]
@sofar I PMed @TalkLounge on the forums, he said he won't maintain it anymore. The last commit was just the upload of their code, so someone can pick it up.
And he said when someone wants to pick it up, he can relicense it.

**Comment by Niwla23** [comment]
And: The license seems to allow redistribution and forking, so i see no problem in adding it, without @TalkLounge s permission

**Comment by sofar** [comment]
It's NC. Sorry, Not acceptable.

**Comment by Niwla23** [comment]
@sofar what means NC?

**Comment by Niwla23** [comment]
@sofar i already wrote @TalkLounge said he might relicense it, so under which license should it be?

**Comment by sofar** [comment]
The easiest way to handle this IMHO:

@talklounge does these steps:
- `git revert 2dc0a82ecb82bb018f04c899d6beaa1532a62ac0`
- `git revert f3b1dbb998e67bf56df8d3d65aa2cb6a523ab275`
or, in other words, revert to the old license (GPL or LGPL for code, CC-BY-SA for artwork)
- push to github
- transfer the repo to `sofar`

**Comment by TalkLounge** [comment]
> in other words, revert to the old license
Don't do that. It has a reason, why it's NC now. Deal with it or ignore the mod.

> I don't think it's abandoned
Sure. I leave/left the minetest community. This issue is another reason, why leaving minetest was a good decision.

**Comment by Niwla23** [comment]
> @Niwla23 Please delete the screenshot in the readme on gitlab, if your license is MIT. My [screenshot](https://user-content.gitlab-static.net/0770553b1fe78bb5372a30b084af08f05e779354/68747470733a2f2f692e696d6775722e636f6d2f356c71344335452e6a7067) is licensed as CC BY-NC 3.0 as well.
> And please update the license in your readme to MIT. That's confusing, if the license file is MIT, but the readme says CC BY-NC 3.0.

ok, i will do also when this is silly from you, hey its a screenshot, on click

**Comment by sofar** [comment]
@talklounge thanks for replying back.

From your reply I can conclude that you're not willing to cooperate and that my proposed (best from my point of view) solution is not something you wish to cooperate with. This is entirely up to you, so, I won't push this any further.

@Niwla23 because of the above decision by @talklounge, the aforemented solution no longer is usable. However, there is a secondary solution that is acceptable:

1. Clone https://github.com/TalkLounge/plot_system/commit/795cd3aca7944d05b7ec7895df45a8eba12bcc37

This code is still licensed in an acceptable way. That version can then be migrated into `minetest-mods` as it contains no `NC` assets. You have to assure that none of the commits after `795cd3ac` are in the repo.

2. Transfer this to `sofar`.

**Comment by Niwla23** [comment]
@sofar I started rewriting the code again, i think it wont make sense too use the first version, its to buggy. SO heres my rewrite of the mapgen:
https://gitlab.com/Niwla23/plot_system
For now its really just mapgen no protection.
I think i have to move it to github and then transfer it to you, right?
PS: It contains no original code

**Comment by sofar** [comment]
So, I'm going to close *this* report.

@Niwla23 you can take your time writing the mod and getting it to a point where it can be used by others - once it is "good enough" you can open a new request for transferring that code.
