### ISSUE TITLE
New mod request: enhanced_builtin_commands

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/minetest-mods.github.io#81]
Name: [enhanced_builtin_commands](https://github.com/Panquesito7/enhanced_builtin_commands)
Author: Panquesito7.
License: LGPLv2.1+ for everything.

**Comment by sofar** [comment]
:+1: - transfer to `sofar` so it can be moved through!

**Comment by Panquesito7** [comment]
Hi @sofar.
Transfer initiated.
