### ISSUE TITLE
Links to VanessaE's mods should be updated

### ISSUE THREAD

**Issue by MarSoft** [minetest-mods/minetest-mods.github.io#82]
Related: #72 
Currently some links from http://minetest-mods.github.io/mods.html#P are dead. One of them is `pipeworks`.
I think we should update these links to point to GitLab.

**Comment by sofar** [comment]
Please submit a patch. My time is currently limited and a PR is a great way to get this solved quickly.

**Comment by SmallJoker** [comment]
The list fetches the minetest-mods projects and shows them on that page automatically. Issue seems to be solved.
