### ISSUE TITLE
New mod request

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest-mods/minetest-mods.github.io#86]
- lavastuff (https://github.com/LoneWolfHT/lavastuff)
- Me
- MIT, CC BY-SA 3.0 and 4.0

I'm focusing on other mods now. It'd be nice to know people are maintaining this (Which I still might help out with)

I'm new to this process so I might need a little help with some things

**Comment by sofar** [comment]
Approved. Initiate a github transfer of the project to `sofar` - I'll take care of moving it into minetest-mods. You'll keep access.

**Comment by LoneWolfHT** [comment]
Done

**Comment by sofar** [comment]
I apologize, the transfer expired before I could accept it. Can you resubmit it, please?

**Comment by LoneWolfHT** [comment]
Done

**Comment by LoneWolfHT** [comment]
Looks like it worked, thanks
