### ISSUE TITLE
New mod request: commoditymarket

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#87]
Mod name: commoditymarket
Author: FaceDeer
License: MIT

This mod (https://github.com/FaceDeer/commoditymarket) is a library back-end mod that allows for the registration and display of game-wide marketplaces, allowing players to buy and sell items with organic supply and demand setting the prices.

There'll be a second mod request coming shortly that has a set of "default" markets built on this library.

**Comment by sofar** [comment]
I'll try and check all of these out tomorrow. Sorry for slow.

**Comment by FaceDeer** [comment]
S'okay. I was starting to wonder, but I'm not in a rush. I figured I'd find someone to poke at the one month mark. :)

**Comment by FaceDeer** [comment]
I just tried setting up a webhook for the minetest-mods version of the repo over on the Content DB and it refused. I don't see a "settings" link at https://github.com/minetest-mods/commoditymarket , am I not fully set up yet?

**Comment by sofar** [comment]
By default when you migrate repos, some permission bits are lost. Usually it doesn't matter, but I'll set it up so you get full admin rights again. ping me if I miss one
