### ISSUE TITLE
New mod request: commoditymarket_fantasy

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#88]
Mod name: commoditymarket_fantasy
Author: FaceDeer
License: MIT

https://github.com/FaceDeer/commoditymarket_fantasy is a set of various fantasy-themed "default" marketplaces based on the commoditymarket library.

**Comment by sofar** [comment]
I don't see a license for the model. Approved permitted you fix that with an appropriate license

**Comment by FaceDeer** [comment]
Whoops. I'll update that momentarily. Figure I'll wait on the answer to my CC0 question in the death_compass request first though, since this is an art asset and therefore CC0 is my default for such things.

**Comment by FaceDeer** [comment]
Actually, since I already put commoditymarket up for transfer I'll update this one and send it too. Can relicense stuff later.

**Comment by sofar** [comment]
CC0 is acceptable, but, I still advise against it in all cases.
