### ISSUE TITLE
Jukebox

### ISSUE THREAD

**Issue by lightonflux** [minetest-mods/minetest-mods.github.io#9]
Hi,

afaik there are 4 jukebox mods for minetest. 

 * Jukebox by Blockman (?)
 * [jdukebox](https://github.com/Jordach/jdukebox/) by jordach (last commit 2 years ago)
 * [Jukebox (plus)](https://github.com/LNJplus/jukebox) by LNJplus (2 months ago)
 * [Jukebox](https://github.com/jordan4ibanez/) by Jordan4Ibanez (9 months ago)

It is not very clear how they differentiate. And 2 of them are unmaintained for longer than a year. 

As far as i can tell the difference between Blockman's mod and Jukebox Plus is that Jukebox Plus supports multiple discs, but does not provide music or recipes for 9 of the 10 discs.

I think it would be beneficial to have one simple and working jukebox mod in minetest-mods.

**Comment by sofar** [comment]
- The original jukebox mod by BlockMen was only posted as zip file. 
- LNJplus' version is derivative of BLockMen's version, and looks maintained
- jordan4ibanez' version looks independent
- jordach's version also looks independent.

@jordach, @jordan4ibanez, @LNJplus - are any of you interested in co-maintaining a version together under minetest-mods?

**Comment by LNJplus** [comment]
Yeah, seems to be a good idea. But at the moment I prefer it work on my game minetest_tng, but in general yes! :smiley:

**Comment by sofar** [comment]
@LNJplus it doesn't need to be you doing all the work.

@jordach, @jordan4ibanez are you interested in working to gether with lnjplus to merge all 3 jukebox mods into one?

**Comment by sofar** [comment]
The minetest-mods group is happy to see if mod owners can be encouraged to post their mods to the group. In this case, I hope LNJ2 will consider doing that. As for Jordach and jordan4ibanez, they likely have more mods that they should contribute, but it's up to them to initiate the request to do so. I can't do much more then encourage it.

**Comment by sofar** [comment]
Closed due to no action required for the minetest-mods team.

**Comment by LNJ2** [comment]
As I said I'm very busy with my game Minetest TNG at the moment, but later (maybe in two or three months) I'm sure I'll do that.

**Comment by LNJ2** [comment]
I would like to move my mod to minetest-mods now! :smiley: 
@sofar

**Comment by sofar** [comment]
@LNJ2 go ahead and transfer it to user "sofar", and I'll transfer it to minetest-mods.

**Comment by LNJ2** [comment]
Ok, done
