### ISSUE TITLE
New mod request: death_compass

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#90]
Name: death_compass
Author: FaceDeer (though see below)
License: MIT

This mod started off life as a fork of ccompass (https://github.com/minetest-mods/ccompass), but I tore it down to its foundations and rewrote it into a very different sort of mod that doesn't really compete with the original - they do different things.

Basically, ccompass provides the user with a compass item that they can lock on to a location with and then always know the direction to get there. death_compass provides the user with a temporary compass (duration depends on configurable settings) that points towards where they last died. The idea is to help players find their way back to their bones, or to that cool thing they saw moments before the giant spider ate them or whatever. I gave death_compass all-new art assets and there's a bunch of new code in it for handling its special purpose.

Since they share a common functionality of "point toward place" I found it convenient to start by forking ccompass, hopefully the reworking I did is extensive enough to let this count as a separate mod in its own right?

**Comment by sofar** [comment]
https://github.com/FaceDeer/death_compass URL missing :)

Approved. I'd prefer no CC0 myself but it's acceptable nonetheless (maybe make your own art CC-BY and keep the rest CC0?)

**Comment by FaceDeer** [comment]
I prefer to release my stuff with as permissive a license as possible. Particularly things like textures, which are most likely to be easily reused by other modders (and which frankly take a lot less work to make than the code for most mods). I can dual-license it to a CC-BY license if you like.

I'm curious, what's wrong with CC0?

**Comment by sofar** [comment]
read my forum threads on licensing - CC0 can be interpreted as "Public Domain" which has negative side effects.

**Comment by FaceDeer** [comment]
Looks like this mod hasn't made it over to minetest-mods yet. Is there a problem with it being a fork of ccompass, which is already over there, perhaps?

**Comment by sofar** [comment]
Yes, I didn't catch that.

I severed the fork. You need to go in and change the project description and URL fields. Otherwise it should be OK. Please check though, I kept the original project in /sofar/ to make sure we can always redo this step (github support can also help here, if it's needed).

**Comment by FaceDeer** [comment]
I think I can probably find all the references to it in forums and whatnot and update them to the minetest-mods URL. There's two people who starred the original repo that don't have a star on the minetest-mods repo, though, I'll try to contact them and let them know what happened. Looks like the commit history was preserved, so that's good.

Would github support be able to make the old URLs go straight to the minetest-mods repo? That might be worth asking them for help with.

**Comment by FaceDeer** [comment]
Okay, just found both of the star-givers on the forum and sent them PMs. Also updated the link. Might be best to just get rid of the leftover repo, if it can't be forwarded to the new location.

**Comment by sofar** [comment]
ok, will do, thanks
