### ISSUE TITLE
New mod request: footprints

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#94]
Mod name: footprints
Author: FaceDeer, paramat, Casimir (see below)
License: MIT

This mod has a bit of a pedigree. It started out in 2012 as a mod named "desire paths" by Casimir. Paramat took it over and developed it for a while, but eventually the mod languished. It was missing support for some of the default mod's new soil types and I wanted to use it with some soil types in another mod I was working on as well.

So I revamped it extensively, adding an external API that other mods could use to register "trampleable" soil types and adding a more sophisticated mechanism for tracking how much soil had been walked on before turning it into hard-packed earth. I sent the changes back as [a pull request](https://github.com/paramat/trail/pull/5), but paramat says he's not maintaining that mod any more and suggested I fork it into my own version.

I've done so, renaming it "footprints" (surprisingly there doesn't seem to be a mod of that name yet). The minetest-mods project guidelines say "Under circumstances (abandoned, author not responsive etc.) we will consider forks." Hopefully this counts as "abandoned"?

**Comment by sofar** [comment]
https://github.com/FaceDeer/footprints
