### ISSUE TITLE
New mod request: update_translations (does this actually fall under this project's purview?)

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/minetest-mods.github.io#95]
Mod name: https://github.com/FaceDeer/update_translations
Authors: Joachim Stolberg, FaceDeer, Louis Royer
License: LGPLv2.1+

Source: https://github.com/FaceDeer/update_translations
Some forum discussion can be found here: https://forum.minetest.net/viewtopic.php?f=47&t=23330&p=367304

This is not actually a mod, it's a modding tool. I actually have no idea if this is appropriate for the minetest-mods project so this issue is kind of speculative. If you know of a better place for it to go I'd be happy sending it somewhere else.

This Python script is a one-click tool for collecting translatable strings from a mod, creating a /locale/template.txt file, updating existing .tr files, and migrating strings from existing .po files. The idea is that you can drop the .py script into the root folder of a mod and then just run it whenever there's been any changes to the strings in the mod. It supports comments associated with individual translatable lines in the template.txt and the .tr files, preserving them when it runs.

**Comment by sofar** [comment]
Sorry for not checking in these yet. There is a `minetest-tools` org as well, perhaps it fits better there?

**Comment by FaceDeer** [comment]
Ah, yes, that does seem like a much better place for it. How do I submit this repo to it? https://github.com/minetest-tools seems to be the place, but there's no "open request" link or equivalent.

**Comment by sofar** [comment]
Transfer the repos to `sofar`. I will transfer all of them through to the right place, so, most will go itno minetest-mods and this one will go into minetest-tools
