### ISSUE TITLE
I leave minetest-mods and minetest.

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest-mods/minetest-mods.github.io#96]
I no longer maintain my mods, so I'm looking for maintainer instead of me.
There is only one target mod (already in minetest-mods): https://github.com/minetest-mods/character_creator
(Other mods of mine are archived in the forum.)

Once this is done, I'm going to close my github account.

**Comment by sofar** [comment]
There's no need to do anything here. You can close your github account without further action.

The community will be able to maintain the repo going forward whether you're here or not. It's nice that you let us know!
