### ISSUE TITLE
New mod request: vehicle_mash

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/minetest-mods.github.io#99]
- Name: [`vehicle_mash`](https://github.com/Panquesito7/vehicle_mash)
- Author: @blert2112, forked and improved by @Panquesito7.
- License: see [`LICENSE.md`](https://github.com/Panquesito7/vehicle_mash/blob/master/LICENSE.md) for information.

The author seems to be not maintaining the mod anymore.
I've made some improvements; and I think this will fit well in Minetest Mods. 🙂

**Comment by sofar** [comment]
Did you contact @blert2112 and ask him for comment? Maybe open an issue against his original project. It's always good to check and reach out to people first.

**Comment by Panquesito7** [comment]
I've contacted him via email.
I've asked him if the project is abandoned and if I can move it to Minetest Mods.

Will ping you when he has given an answer.

**Comment by blert2112** [comment]
Hey folks. Really sorry that I am not tending to these mods anymore. But hey! At least I didn't just strip them from my github repositories. Please, do as you wish with them. Spread the word. If you use them fork them and do as you wish. Please note that most of them are based on previous works but should have all the details in the Readme files. The license info was valid and up to date at the time each mod was released but may have changed since then (was quite a while ago) so you might want to check into that if you decide to re-release them.

**Comment by Panquesito7** [comment]
Thanks @blert2112 for the information.
I have checked the licenses of each mods, and all licenses are up-to-date.

**Comment by Panquesito7** [comment]
@sofar ping.

**Comment by sofar** [comment]
@blert2112 would you be willing to transfer your mods to into the minetest-mods org so the history and redirects are and remain in place? That way @Panquesito7 can still submit his additional changes and users will have an easy time finding the updated version. If you're OK with that, start the github transfer to `sofar` - if not, we'll take @Panquesito7 's fork but generally I prefer not to take forks (merging forks is always better).

**Comment by blert2112** [comment]
Yeah, I have no problem with that at all. I will be 100% honest with you though... I don't know how to transfer the repos to you. As soon as I can get all these people out of my house and get to my laptop I will look into it.

**Comment by Panquesito7** [comment]
@blert2112, see [GitHub Help](https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) for how to transfer a repository. 🙂

**Comment by blert2112** [comment]
Thanks. Found it with a quick search. You guys want all of them or do you want to give me a list?

**Comment by Panquesito7** [comment]
If you want all of your mods to be moved to the organization, it's all fine.
I was only asking for `lib_mount` and `vehicle_mash` to be moved, though.

**Comment by blert2112** [comment]
"Done and done."
Those two anyway. I will transfer the rest of the working mods, no problem. I dont want to pound @sofar with a bunch of transfers unless he wants them though. Let me know.
